/**
 * CCBalance - 关卡数据模块
 * 包含所有高中化学方程式关卡
 */

const LevelData = {
    // 关卡分类
    categories: {
        ionic: {
            name: '离子反应',
            icon: 'fa-bolt',
            description: '离子交换与沉淀反应',
            color: '#00d4ff'
        },
        redox: {
            name: '氧化还原',
            icon: 'fa-exchange-alt',
            description: '电子转移反应',
            color: '#ff00aa'
        },
        dissolution: {
            name: '溶解平衡',
            icon: 'fa-tint',
            description: '沉淀溶解平衡',
            color: '#ffaa00'
        },
        ionization: {
            name: '电离水解',
            icon: 'fa-water',
            description: '弱电解质电离与盐类水解',
            color: '#00ff88'
        },
        complex: {
            name: '综合反应',
            icon: 'fa-puzzle-piece',
            description: '复杂化学平衡',
            color: '#7b2dff'
        },
        electrochemistry: {
            name: '电化学',
            icon: 'fa-battery-three-quarters',
            description: '原电池与电解池反应',
            color: '#ff6b00'
        },
        organic: {
            name: '有机反应',
            icon: 'fa-flask',
            description: '有机化合物转化平衡',
            color: '#00d47f'
        },
        custom: {
            name: '自定义',
            icon: 'fa-wrench',
            description: '创意工坊自定义关卡',
            color: '#00d4ff'
        }
    },

    /**
     * 调整初始浓度使Q=K
     */
    adjustInitialConcentrations(level, temperature = null) {
        const T = temperature ?? level.initialTemp ?? 298;
        const KRaw = (typeof ChemistryEngine !== 'undefined' && ChemistryEngine.calculateK)
            ? ChemistryEngine.calculateK(level, T)
            : (level.equilibriumConstant ?? 1);

        const K = (Number.isFinite(KRaw) && KRaw > 0) ? KRaw : 1;
        const reactants = level.reactants || [];
        const products = level.products || [];
        const coef = level.coefficients || {};

        // Q = Π[prod]^ν / Π[react]^ν
        // 令所有产物浓度 = 10^a，所有反应物浓度 = 10^b
        // 则 log10(Q) = a*P - b*R，取 a = logK/(P+R), b = -logK/(P+R) 可保证 Q=K 且两边“对称”
        const sumPower = (list) => list.reduce((acc, s) => acc + (coef[s] ?? 1), 0);
        const R = sumPower(reactants);
        const P = sumPower(products);

        if (R <= 0 || P <= 0) {
            return { ...(level.initialConcentrations || {}) };
        }

        const logK = Math.log10(K);
        const denom = P + R;
        const a = logK / denom;
        const b = -logK / denom;

        const prodConc = Math.pow(10, a);
        const reacConc = Math.pow(10, b);

        const newConc = {};
        for (const r of reactants) newConc[r] = reacConc;
        for (const p of products) newConc[p] = prodConc;

        // 补齐可能存在但未出现在方程式列表里的物种（兜底）
        if (level.initialConcentrations) {
            for (const [k, v] of Object.entries(level.initialConcentrations)) {
                if (newConc[k] === undefined) newConc[k] = v;
            }
        }

        // 保证数值合法
        for (const key of Object.keys(newConc)) {
            const v = newConc[key];
            if (!Number.isFinite(v) || v <= 0) newConc[key] = 1;
        }

        return newConc;
    },

    // 关卡列表
    levels: [
        // ===== 离子反应 (1-20) =====
        {
            id: 1,
            category: 'ionic',
            equation: 'H+ + OH- = H2O',
            displayEquation: 'H<sup>+</sup> + OH<sup>-</sup> ⇌ H<sub>2</sub>O',
            name: '酸碱中和',
            description: '最基本的中和反应',
            poeticDescription: '阴阳相遇，水润无声，和合之道始于此',
            reactants: ['H+', 'OH-'],
            products: ['H2O'],
            coefficients: { 'H+': 1, 'OH-': 1, 'H2O': 1 },
            initialConcentrations: { 'H+': 1, 'OH-': 1, 'H2O': 1 },
            equilibriumConstant: 1e14,
            deltaH: -57.3,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 1
        },
        {
            id: 2,
            category: 'ionic',
            equation: 'Ba2+ + SO42- = BaSO4',
            displayEquation: 'Ba<sup>2+</sup> + SO<sub>4</sub><sup>2-</sup> ⇌ BaSO<sub>4</sub>↓',
            name: '硫酸钡沉淀',
            description: '难溶盐沉淀反应',
            poeticDescription: '重晶石沉，白练舞空，天地之固化身',
            reactants: ['Ba2+', 'SO42-'],
            products: ['BaSO4'],
            coefficients: { 'Ba2+': 1, 'SO42-': 1, 'BaSO4': 1 },
            initialConcentrations: { 'Ba2+': 0.5, 'SO42-': 0.5, 'BaSO4': 0.01 },
            equilibriumConstant: 1e10,
            deltaH: -20,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 1
        },
        {
            id: 3,
            category: 'ionic',
            equation: 'Ag+ + Cl- = AgCl',
            displayEquation: 'Ag<sup>+</sup> + Cl<sup>-</sup> ⇌ AgCl↓',
            name: '氯化银沉淀',
            description: '卤化银沉淀反应',
            poeticDescription: '银氯结晶，光感之源，暗室成像起锋芒',
            reactants: ['Ag+', 'Cl-'],
            products: ['AgCl'],
            coefficients: { 'Ag+': 1, 'Cl-': 1, 'AgCl': 1 },
            initialConcentrations: { 'Ag+': 0.5, 'Cl-': 0.5, 'AgCl': 0.01 },
            equilibriumConstant: 1e10,
            deltaH: -65,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 1
        },
        {
            id: 4,
            category: 'ionic',
            equation: 'Ca2+ + CO32- = CaCO3',
            displayEquation: 'Ca<sup>2+</sup> + CO<sub>3</sub><sup>2-</sup> ⇌ CaCO<sub>3</sub>↓',
            name: '碳酸钙沉淀',
            description: '碳酸盐沉淀反应',
            poeticDescription: '钙碳凝结，山河骨骼，亿年沉积铸坚岩',
            reactants: ['Ca2+', 'CO32-'],
            products: ['CaCO3'],
            coefficients: { 'Ca2+': 1, 'CO32-': 1, 'CaCO3': 1 },
            initialConcentrations: { 'Ca2+': 0.5, 'CO32-': 0.5, 'CaCO3': 0.01 },
            equilibriumConstant: 1e8,
            deltaH: -13,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 1
        },
        {
            id: 5,
            category: 'ionic',
            equation: 'Fe3+ + 3OH- = Fe(OH)3',
            displayEquation: 'Fe<sup>3+</sup> + 3OH<sup>-</sup> ⇌ Fe(OH)<sub>3</sub>↓',
            name: '氢氧化铁沉淀',
            description: '氢氧化物沉淀反应',
            poeticDescription: '铁羟赤褐，锈色花开，三价金属显威严',
            reactants: ['Fe3+', 'OH-'],
            products: ['Fe(OH)3'],
            coefficients: { 'Fe3+': 1, 'OH-': 3, 'Fe(OH)3': 1 },
            initialConcentrations: { 'Fe3+': 0.3, 'OH-': 0.5, 'Fe(OH)3': 0.01 },
            equilibriumConstant: 1e38,
            deltaH: -100,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 6,
            category: 'ionic',
            equation: 'Cu2+ + 2OH- = Cu(OH)2',
            displayEquation: 'Cu<sup>2+</sup> + 2OH<sup>-</sup> ⇌ Cu(OH)<sub>2</sub>↓',
            name: '氢氧化铜沉淀',
            description: '蓝色氢氧化物沉淀',
            poeticDescription: '蓝铜晶莹，天青之色，碱遇金属生灵华',
            reactants: ['Cu2+', 'OH-'],
            products: ['Cu(OH)2'],
            coefficients: { 'Cu2+': 1, 'OH-': 2, 'Cu(OH)2': 1 },
            initialConcentrations: { 'Cu2+': 0.4, 'OH-': 0.6, 'Cu(OH)2': 0.01 },
            equilibriumConstant: 1e19,
            deltaH: -50,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 7,
            category: 'ionic',
            equation: 'Mg2+ + 2OH- = Mg(OH)2',
            displayEquation: 'Mg<sup>2+</sup> + 2OH<sup>-</sup> ⇌ Mg(OH)<sub>2</sub>↓',
            name: '氢氧化镁沉淀',
            description: '白色氢氧化物沉淀',
            poeticDescription: '镁羟素雪，白如凝霜，碱土金属展柔情',
            reactants: ['Mg2+', 'OH-'],
            products: ['Mg(OH)2'],
            coefficients: { 'Mg2+': 1, 'OH-': 2, 'Mg(OH)2': 1 },
            initialConcentrations: { 'Mg2+': 0.4, 'OH-': 0.6, 'Mg(OH)2': 0.01 },
            equilibriumConstant: 1e11,
            deltaH: -40,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 8,
            category: 'ionic',
            equation: 'CO32- + 2H+ = H2O + CO2',
            displayEquation: 'CO<sub>3</sub><sup>2-</sup> + 2H<sup>+</sup> ⇌ H<sub>2</sub>O + CO<sub>2</sub>↑',
            name: '碳酸盐与酸反应',
            description: '产生二氧化碳气体',
            poeticDescription: '碳酸逢酸，气泡升腾，二氧化碳破浪行',
            reactants: ['CO32-', 'H+'],
            products: ['H2O', 'CO2'],
            coefficients: { 'CO32-': 1, 'H+': 2, 'H2O': 1, 'CO2': 1 },
            initialConcentrations: { 'CO32-': 0.5, 'H+': 0.8, 'H2O': 1, 'CO2': 0.1 },
            equilibriumConstant: 1e16,
            deltaH: -30,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO2'],
            difficulty: 2
        },
        {
            id: 9,
            category: 'ionic',
            equation: 'S2- + 2H+ = H2S',
            displayEquation: 'S<sup>2-</sup> + 2H<sup>+</sup> ⇌ H<sub>2</sub>S↑',
            name: '硫化物与酸反应',
            description: '产生硫化氢气体',
            poeticDescription: '硫化释氢，臭气冲天，地狱之门启幽冥',
            reactants: ['S2-', 'H+'],
            products: ['H2S'],
            coefficients: { 'S2-': 1, 'H+': 2, 'H2S': 1 },
            initialConcentrations: { 'S2-': 0.4, 'H+': 0.6, 'H2S': 0.1 },
            equilibriumConstant: 1e20,
            deltaH: -20,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2S'],
            difficulty: 2
        },
        {
            id: 10,
            category: 'ionic',
            equation: 'NH4+ + OH- = NH3·H2O',
            displayEquation: 'NH<sub>4</sub><sup>+</sup> + OH<sup>-</sup> ⇌ NH<sub>3</sub>·H<sub>2</sub>O',
            name: '铵盐与碱反应',
            description: '生成一水合氨',
            poeticDescription: '铵遇强碱，氨水横生，挥发之性展锋芒',
            reactants: ['NH4+', 'OH-'],
            products: ['NH3·H2O'],
            coefficients: { 'NH4+': 1, 'OH-': 1, 'NH3·H2O': 1 },
            initialConcentrations: { 'NH4+': 0.5, 'OH-': 0.5, 'NH3·H2O': 0.1 },
            equilibriumConstant: 1e9,
            deltaH: -35,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },

        // ===== 离子反应补齐 (11-20) =====
        {
            id: 11,
            category: 'ionic',
            equation: 'Pb2+ + 2I- = PbI2',
            displayEquation: 'Pb<sup>2+</sup> + 2I<sup>-</sup> ⇌ PbI<sub>2</sub>↓',
            name: '碘化铅沉淀',
            description: '黄色沉淀生成',
            poeticDescription: '铅碘金黄，艳若朝阳，卤化物中显光华',
            reactants: ['Pb2+', 'I-'],
            products: ['PbI2'],
            coefficients: { 'Pb2+': 1, 'I-': 2, 'PbI2': 1 },
            initialConcentrations: { 'Pb2+': 0.3, 'I-': 0.8, 'PbI2': 0.01 },
            equilibriumConstant: 1e12,
            deltaH: -30,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 2
        },
        {
            id: 12,
            category: 'ionic',
            equation: 'Cu2+ + CO32- = CuCO3',
            displayEquation: 'Cu<sup>2+</sup> + CO<sub>3</sub><sup>2-</sup> ⇌ CuCO<sub>3</sub>↓',
            name: '碳酸铜沉淀',
            description: '生成碱式碳酸盐沉淀的简化模型',
            poeticDescription: '铜碳青翠，孔雀之石，古铜器上绿锈生',
            reactants: ['Cu2+', 'CO32-'],
            products: ['CuCO3'],
            coefficients: { 'Cu2+': 1, 'CO32-': 1, 'CuCO3': 1 },
            initialConcentrations: { 'Cu2+': 0.4, 'CO32-': 0.4, 'CuCO3': 0.01 },
            equilibriumConstant: 1e9,
            deltaH: -25,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 2
        },
        {
            id: 13,
            category: 'ionic',
            equation: 'Al3+ + 3OH- = Al(OH)3',
            displayEquation: 'Al<sup>3+</sup> + 3OH<sup>-</sup> ⇌ Al(OH)<sub>3</sub>↓',
            name: '氢氧化铝沉淀',
            description: '两性氢氧化物沉淀（简化为沉淀生成）',
            poeticDescription: '铝羟两性，进退有度，既酸既碱显神通',
            reactants: ['Al3+', 'OH-'],
            products: ['Al(OH)3'],
            coefficients: { 'Al3+': 1, 'OH-': 3, 'Al(OH)3': 1 },
            initialConcentrations: { 'Al3+': 0.2, 'OH-': 0.9, 'Al(OH)3': 0.01 },
            equilibriumConstant: 1e30,
            deltaH: -40,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 2
        },
        {
            id: 14,
            category: 'ionic',
            equation: 'Fe2+ + 2OH- = Fe(OH)2',
            displayEquation: 'Fe<sup>2+</sup> + 2OH<sup>-</sup> ⇌ Fe(OH)<sub>2</sub>↓',
            name: '氢氧化亚铁沉淀',
            description: '浅绿色沉淀（简化模型）',
            poeticDescription: '亚铁绿色，风化易变，二价铁离淡如梦',
            reactants: ['Fe2+', 'OH-'],
            products: ['Fe(OH)2'],
            coefficients: { 'Fe2+': 1, 'OH-': 2, 'Fe(OH)2': 1 },
            initialConcentrations: { 'Fe2+': 0.3, 'OH-': 0.6, 'Fe(OH)2': 0.01 },
            equilibriumConstant: 1e14,
            deltaH: -35,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 2
        },
        {
            id: 15,
            category: 'ionic',
            equation: 'Zn2+ + S2- = ZnS',
            displayEquation: 'Zn<sup>2+</sup> + S<sup>2-</sup> ⇌ ZnS↓',
            name: '硫化锌沉淀',
            description: '难溶硫化物沉淀',
            poeticDescription: '锌硫结合，白色难溶，硫化物中藏玄机',
            reactants: ['Zn2+', 'S2-'],
            products: ['ZnS'],
            coefficients: { 'Zn2+': 1, 'S2-': 1, 'ZnS': 1 },
            initialConcentrations: { 'Zn2+': 0.4, 'S2-': 0.4, 'ZnS': 0.01 },
            equilibriumConstant: 1e22,
            deltaH: -20,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 2
        },
        {
            id: 16,
            category: 'ionic',
            equation: 'Ca2+ + 2F- = CaF2',
            displayEquation: 'Ca<sup>2+</sup> + 2F<sup>-</sup> ⇌ CaF<sub>2</sub>↓',
            name: '氟化钙沉淀',
            description: '难溶盐沉淀反应',
            poeticDescription: '氟钙结晶，牙齿之基，微溶之质护齿康',
            reactants: ['Ca2+', 'F-'],
            products: ['CaF2'],
            coefficients: { 'Ca2+': 1, 'F-': 2, 'CaF2': 1 },
            initialConcentrations: { 'Ca2+': 0.25, 'F-': 0.8, 'CaF2': 0.01 },
            equilibriumConstant: 1e10,
            deltaH: -18,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 3
        },
        {
            id: 17,
            category: 'ionic',
            equation: '2H+ + SO32- = H2O + SO2',
            displayEquation: '2H<sup>+</sup> + SO<sub>3</sub><sup>2-</sup> ⇌ H<sub>2</sub>O + SO<sub>2</sub>↑',
            name: '亚硫酸盐与酸反应',
            description: '放出二氧化硫气体',
            poeticDescription: '亚硫遇酸，二氧化硫，刺激气味显其性',
            reactants: ['H+', 'SO32-'],
            products: ['H2O', 'SO2'],
            coefficients: { 'H+': 2, 'SO32-': 1, 'H2O': 1, 'SO2': 1 },
            initialConcentrations: { 'H+': 0.8, 'SO32-': 0.4, 'H2O': 1, 'SO2': 0.1 },
            equilibriumConstant: 1e14,
            deltaH: -35,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['SO2'],
            containerType: 'flexible',
            difficulty: 3
        },
        {
            id: 18,
            category: 'ionic',
            equation: 'HCO3- + H+ = H2O + CO2',
            displayEquation: 'HCO<sub>3</sub><sup>-</sup> + H<sup>+</sup> ⇌ H<sub>2</sub>O + CO<sub>2</sub>↑',
            name: '碳酸氢盐与酸反应',
            description: '产生二氧化碳气体',
            poeticDescription: '碳酸氢根，遇酸分解，气泡翻涌二氧腾',
            reactants: ['HCO3-', 'H+'],
            products: ['H2O', 'CO2'],
            coefficients: { 'HCO3-': 1, 'H+': 1, 'H2O': 1, 'CO2': 1 },
            initialConcentrations: { 'HCO3-': 0.6, 'H+': 0.6, 'H2O': 1, 'CO2': 0.1 },
            equilibriumConstant: 1e12,
            deltaH: -25,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO2'],
            containerType: 'flexible',
            difficulty: 3
        },
        {
            id: 19,
            category: 'ionic',
            equation: 'Mg2+ + 2Cl- = MgCl2',
            displayEquation: 'Mg<sup>2+</sup> + 2Cl<sup>-</sup> ⇌ MgCl<sub>2</sub>',
            name: '离子缔合（示例）',
            description: '用于练习系数与Q/K（简化为缔合）',
            poeticDescription: '氯化锌溶，金属腐蚀，焊接助剂展锋芒',
            reactants: ['Mg2+', 'Cl-'],
            products: ['MgCl2'],
            coefficients: { 'Mg2+': 1, 'Cl-': 2, 'MgCl2': 1 },
            initialConcentrations: { 'Mg2+': 0.4, 'Cl-': 0.8, 'MgCl2': 0.1 },
            equilibriumConstant: 1e4,
            deltaH: -10,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 3
        },
        {
            id: 20,
            category: 'ionic',
            equation: 'H+ + CH3COO- = CH3COOH',
            displayEquation: 'H<sup>+</sup> + CH<sub>3</sub>COO<sup>-</sup> ⇌ CH<sub>3</sub>COOH',
            name: '乙酸根酸化',
            description: '弱酸共轭碱的质子化（简化模型）',
            poeticDescription: '碳酸钠碱，纯碱如玉，工业之母掌乾坤',
            reactants: ['H+', 'CH3COO-'],
            products: ['CH3COOH'],
            coefficients: { 'H+': 1, 'CH3COO-': 1, 'CH3COOH': 1 },
            initialConcentrations: { 'H+': 0.4, 'CH3COO-': 0.6, 'CH3COOH': 0.2 },
            equilibriumConstant: 1e5,
            deltaH: -15,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            containerType: 'flexible',
            difficulty: 3
        },

        // ===== 氧化还原 (21-40) =====
        {
            id: 21,
            category: 'redox',
            equation: '2Fe3+ + Fe = 3Fe2+',
            displayEquation: '2Fe<sup>3+</sup> + Fe ⇌ 3Fe<sup>2+</sup>',
            name: '铁的歧化',
            description: '铁离子与铁反应',
            poeticDescription: '铜遇浓酸，褐烟滚滚，电子转移显化魂',
            reactants: ['Fe3+', 'Fe'],
            products: ['Fe2+'],
            coefficients: { 'Fe3+': 2, 'Fe': 1, 'Fe2+': 3 },
            initialConcentrations: { 'Fe3+': 0.4, 'Fe': 1, 'Fe2+': 0.2 },
            equilibriumConstant: 1e6,
            deltaH: -45,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 22,
            category: 'redox',
            equation: 'Zn + Cu2+ = Zn2+ + Cu',
            displayEquation: 'Zn + Cu<sup>2+</sup> ⇌ Zn<sup>2+</sup> + Cu',
            name: '锌置换铜',
            description: '金属置换反应',
            poeticDescription: '锌投硫酸，氢气泡升，金属活性展雄风',
            reactants: ['Zn', 'Cu2+'],
            products: ['Zn2+', 'Cu'],
            coefficients: { 'Zn': 1, 'Cu2+': 1, 'Zn2+': 1, 'Cu': 1 },
            initialConcentrations: { 'Zn': 1, 'Cu2+': 0.5, 'Zn2+': 0.1, 'Cu': 0.1 },
            equilibriumConstant: 1e37,
            deltaH: -210,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 23,
            category: 'redox',
            equation: 'Cl2 + 2Br- = 2Cl- + Br2',
            displayEquation: 'Cl<sub>2</sub> + 2Br<sup>-</sup> ⇌ 2Cl<sup>-</sup> + Br<sub>2</sub>',
            name: '氯气氧化溴离子',
            description: '卤素置换反应',
            poeticDescription: '铁入铜盐，置换轮回，强者夺取弱者魂',
            reactants: ['Cl2', 'Br-'],
            products: ['Cl-', 'Br2'],
            coefficients: { 'Cl2': 1, 'Br-': 2, 'Cl-': 2, 'Br2': 1 },
            initialConcentrations: { 'Cl2': 0.3, 'Br-': 0.6, 'Cl-': 0.1, 'Br2': 0.1 },
            equilibriumConstant: 1e10,
            deltaH: -90,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['Cl2'],
            difficulty: 2
        },
        {
            id: 24,
            category: 'redox',
            equation: '2Fe2+ + Cl2 = 2Fe3+ + 2Cl-',
            displayEquation: '2Fe<sup>2+</sup> + Cl<sub>2</sub> ⇌ 2Fe<sup>3+</sup> + 2Cl<sup>-</sup>',
            name: '氯气氧化亚铁',
            description: '氯气的氧化性',
            poeticDescription: '高锰褪色，氧化之王，紫红渐淡显神通',
            reactants: ['Fe2+', 'Cl2'],
            products: ['Fe3+', 'Cl-'],
            coefficients: { 'Fe2+': 2, 'Cl2': 1, 'Fe3+': 2, 'Cl-': 2 },
            initialConcentrations: { 'Fe2+': 0.5, 'Cl2': 0.25, 'Fe3+': 0.1, 'Cl-': 0.2 },
            equilibriumConstant: 1e12,
            deltaH: -100,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['Cl2'],
            difficulty: 3
        },
        {
            id: 25,
            category: 'redox',
            equation: 'MnO4- + 5Fe2+ + 8H+ = Mn2+ + 5Fe3+ + 4H2O',
            displayEquation: 'MnO<sub>4</sub><sup>-</sup> + 5Fe<sup>2+</sup> + 8H<sup>+</sup> ⇌ Mn<sup>2+</sup> + 5Fe<sup>3+</sup> + 4H<sub>2</sub>O',
            name: '高锰酸钾氧化亚铁',
            description: '经典氧化还原滴定',
            poeticDescription: '氯气漂白，黄绿如烟，强氧化性震乾坤',
            reactants: ['MnO4-', 'Fe2+', 'H+'],
            products: ['Mn2+', 'Fe3+', 'H2O'],
            coefficients: { 'MnO4-': 1, 'Fe2+': 5, 'H+': 8, 'Mn2+': 1, 'Fe3+': 5, 'H2O': 4 },
            initialConcentrations: { 'MnO4-': 0.2, 'Fe2+': 0.6, 'H+': 1, 'Mn2+': 0.05, 'Fe3+': 0.1, 'H2O': 1 },
            equilibriumConstant: 1e60,
            deltaH: -500,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 4
        },
        {
            id: 26,
            category: 'redox',
            equation: 'Cu + 2Ag+ = Cu2+ + 2Ag',
            displayEquation: 'Cu + 2Ag<sup>+</sup> ⇌ Cu<sup>2+</sup> + 2Ag',
            name: '铜置换银',
            description: '金属活动性顺序',
            poeticDescription: '碘遇淀粉，蓝紫深沉，氧化还原色相生',
            reactants: ['Cu', 'Ag+'],
            products: ['Cu2+', 'Ag'],
            coefficients: { 'Cu': 1, 'Ag+': 2, 'Cu2+': 1, 'Ag': 2 },
            initialConcentrations: { 'Cu': 1, 'Ag+': 0.5, 'Cu2+': 0.05, 'Ag': 0.1 },
            equilibriumConstant: 1e15,
            deltaH: -150,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 27,
            category: 'redox',
            equation: '2Fe3+ + Sn2+ = 2Fe2+ + Sn4+',
            displayEquation: '2Fe<sup>3+</sup> + Sn<sup>2+</sup> ⇌ 2Fe<sup>2+</sup> + Sn<sup>4+</sup>',
            name: '铁离子氧化亚锡',
            description: '离子间电子转移',
            poeticDescription: '铝热反应，火光四射，金属夺氧释能狂',
            reactants: ['Fe3+', 'Sn2+'],
            products: ['Fe2+', 'Sn4+'],
            coefficients: { 'Fe3+': 2, 'Sn2+': 1, 'Fe2+': 2, 'Sn4+': 1 },
            initialConcentrations: { 'Fe3+': 0.6, 'Sn2+': 0.3, 'Fe2+': 0.1, 'Sn4+': 0.05 },
            equilibriumConstant: 1e8,
            deltaH: -80,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 28,
            category: 'redox',
            equation: 'I2 + 2S2O32- = 2I- + S4O62-',
            displayEquation: 'I<sub>2</sub> + 2S<sub>2</sub>O<sub>3</sub><sup>2-</sup> ⇌ 2I<sup>-</sup> + S<sub>4</sub>O<sub>6</sub><sup>2-</sup>',
            name: '碘量法滴定',
            description: '碘与硫代硫酸根反应',
            poeticDescription: '铁粉夺氧，蒸汽相遇，氢气奔腾铁自由',
            reactants: ['I2', 'S2O32-'],
            products: ['I-', 'S4O62-'],
            coefficients: { 'I2': 1, 'S2O32-': 2, 'I-': 2, 'S4O62-': 1 },
            initialConcentrations: { 'I2': 0.3, 'S2O32-': 0.6, 'I-': 0.1, 'S4O62-': 0.05 },
            equilibriumConstant: 1e20,
            deltaH: -120,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 29,
            category: 'redox',
            equation: 'H2O2 + 2I- + 2H+ = I2 + 2H2O',
            displayEquation: 'H<sub>2</sub>O<sub>2</sub> + 2I<sup>-</sup> + 2H<sup>+</sup> ⇌ I<sub>2</sub> + 2H<sub>2</sub>O',
            name: '过氧化氢氧化碘离子',
            description: '双氧水的氧化性',
            poeticDescription: '铜投硝酸，气体飞扬，浓淡有别显差异',
            reactants: ['H2O2', 'I-', 'H+'],
            products: ['I2', 'H2O'],
            coefficients: { 'H2O2': 1, 'I-': 2, 'H+': 2, 'I2': 1, 'H2O': 2 },
            initialConcentrations: { 'H2O2': 0.3, 'I-': 0.5, 'H+': 0.8, 'I2': 0.1, 'H2O': 1 },
            equilibriumConstant: 1e18,
            deltaH: -200,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 30,
            category: 'redox',
            equation: 'Br2 + 2I- = 2Br- + I2',
            displayEquation: 'Br<sub>2</sub> + 2I<sup>-</sup> ⇌ 2Br<sup>-</sup> + I<sub>2</sub>',
            name: '溴氧化碘离子',
            description: '卤素间的置换',
            poeticDescription: '锌遇硝酸，八电转移，铵盐初现化归一',
            reactants: ['Br2', 'I-'],
            products: ['Br-', 'I2'],
            coefficients: { 'Br2': 1, 'I-': 2, 'Br-': 2, 'I2': 1 },
            initialConcentrations: { 'Br2': 0.3, 'I-': 0.6, 'Br-': 0.1, 'I2': 0.1 },
            equilibriumConstant: 1e8,
            deltaH: -85,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 31,
            category: 'redox',
            equation: 'Cr2O72- + 14H+ + 6e- = 2Cr3+ + 7H2O',
            displayEquation: 'Cr<sub>2</sub>O<sub>7</sub><sup>2-</sup> + 14H<sup>+</sup> ⇌ 2Cr<sup>3+</sup> + 7H<sub>2</sub>O (简化)',
            name: '重铬酸根还原',
            description: '铬的氧化还原平衡（简化模型）',
            poeticDescription: '过氧分解，氧气涌现，催化之妙展无穷',
            reactants: ['Cr2O72-', 'H+'],
            products: ['Cr3+', 'H2O'],
            coefficients: { 'Cr2O72-': 1, 'H+': 14, 'Cr3+': 2, 'H2O': 7 },
            initialConcentrations: { 'Cr2O72-': 0.1, 'H+': 1.5, 'Cr3+': 0.05, 'H2O': 1 },
            equilibriumConstant: 1e15,
            deltaH: -350,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 4
        },
        {
            id: 32,
            category: 'redox',
            equation: 'SO2 + 2H2S = 3S + 2H2O',
            displayEquation: 'SO<sub>2</sub> + 2H<sub>2</sub>S ⇌ 3S + 2H<sub>2</sub>O',
            name: '二氧化硫与硫化氢',
            description: '硫的归中反应',
            poeticDescription: '钠投于水，火光飞溅，碱金属性最强狂',
            reactants: ['SO2', 'H2S'],
            products: ['S', 'H2O'],
            coefficients: { 'SO2': 1, 'H2S': 2, 'S': 3, 'H2O': 2 },
            initialConcentrations: { 'SO2': 0.3, 'H2S': 0.5, 'S': 0.1, 'H2O': 1 },
            equilibriumConstant: 1e12,
            deltaH: -145,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['SO2', 'H2S'],
            difficulty: 3
        },
        {
            id: 33,
            category: 'redox',
            equation: '2H2O2 = 2H2O + O2',
            displayEquation: '2H<sub>2</sub>O<sub>2</sub> ⇌ 2H<sub>2</sub>O + O<sub>2</sub>↑',
            name: '过氧化氢分解',
            description: '双氧水的自分解',
            poeticDescription: '氯遇碱液，歧化轮回，一分为二显玄机',
            reactants: ['H2O2'],
            products: ['H2O', 'O2'],
            coefficients: { 'H2O2': 2, 'H2O': 2, 'O2': 1 },
            initialConcentrations: { 'H2O2': 0.6, 'H2O': 1, 'O2': 0.1 },
            equilibriumConstant: 1e10,
            deltaH: -98,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['O2'],
            difficulty: 2
        },
        {
            id: 34,
            category: 'redox',
            equation: '2NO + O2 = 2NO2',
            displayEquation: '2NO + O<sub>2</sub> ⇌ 2NO<sub>2</sub>',
            name: '一氧化氮氧化',
            description: '氮氧化物反应',
            poeticDescription: '硫化氢燃，蓝焰摇曳，氧化还原释硫华',
            reactants: ['NO', 'O2'],
            products: ['NO2'],
            coefficients: { 'NO': 2, 'O2': 1, 'NO2': 2 },
            initialConcentrations: { 'NO': 0.5, 'O2': 0.3, 'NO2': 0.1 },
            equilibriumConstant: 1e6,
            deltaH: -114,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['NO', 'O2', 'NO2'],
            difficulty: 3
        },
        {
            id: 35,
            category: 'redox',
            equation: 'Cu2+ + Zn = Cu + Zn2+',
            displayEquation: 'Cu<sup>2+</sup> + Zn ⇌ Cu + Zn<sup>2+</sup>',
            name: '原电池反应',
            description: '铜锌原电池',
            poeticDescription: '亚硫酸盐，还原之力，二氧化硫化学魂',
            reactants: ['Cu2+', 'Zn'],
            products: ['Cu', 'Zn2+'],
            coefficients: { 'Cu2+': 1, 'Zn': 1, 'Cu': 1, 'Zn2+': 1 },
            initialConcentrations: { 'Cu2+': 0.5, 'Zn': 1, 'Cu': 0.1, 'Zn2+': 0.1 },
            equilibriumConstant: 1e37,
            deltaH: -210,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 36,
            category: 'redox',
            equation: 'NO3- + 4H+ + 3e- = NO + 2H2O',
            displayEquation: 'NO<sub>3</sub><sup>-</sup> + 4H<sup>+</sup> ⇌ NO↑ + 2H<sub>2</sub>O (简化)',
            name: '硝酸根还原',
            description: '稀硝酸与金属反应（简化）',
            poeticDescription: '双氧水解，氧气奔腾，过氧之键断裂时',
            reactants: ['NO3-', 'H+'],
            products: ['NO', 'H2O'],
            coefficients: { 'NO3-': 1, 'H+': 4, 'NO': 1, 'H2O': 2 },
            initialConcentrations: { 'NO3-': 0.4, 'H+': 1.2, 'NO': 0.1, 'H2O': 1 },
            equilibriumConstant: 1e12,
            deltaH: -180,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['NO'],
            difficulty: 3
        },
        {
            id: 37,
            category: 'redox',
            equation: 'Mg + 2H+ = Mg2+ + H2',
            displayEquation: 'Mg + 2H<sup>+</sup> ⇌ Mg<sup>2+</sup> + H<sub>2</sub>↑',
            name: '镁与酸反应',
            description: '活泼金属与酸',
            poeticDescription: '铁氰化钾，检验铁踪，普鲁士蓝显神威',
            reactants: ['Mg', 'H+'],
            products: ['Mg2+', 'H2'],
            coefficients: { 'Mg': 1, 'H+': 2, 'Mg2+': 1, 'H2': 1 },
            initialConcentrations: { 'Mg': 1, 'H+': 0.8, 'Mg2+': 0.1, 'H2': 0.1 },
            equilibriumConstant: 1e40,
            deltaH: -465,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2'],
            difficulty: 2
        },
        {
            id: 38,
            category: 'redox',
            equation: '2I- + S2O82- = I2 + 2SO42-',
            displayEquation: '2I<sup>-</sup> + S<sub>2</sub>O<sub>8</sub><sup>2-</sup> ⇌ I<sub>2</sub> + 2SO<sub>4</sub><sup>2-</sup>',
            name: '过二硫酸根氧化碘',
            description: '过二硫酸盐的氧化性',
            poeticDescription: '溴水褪色，双键开裂，加成反应辨有机',
            reactants: ['I-', 'S2O82-'],
            products: ['I2', 'SO42-'],
            coefficients: { 'I-': 2, 'S2O82-': 1, 'I2': 1, 'SO42-': 2 },
            initialConcentrations: { 'I-': 0.5, 'S2O82-': 0.25, 'I2': 0.05, 'SO42-': 0.1 },
            equilibriumConstant: 1e16,
            deltaH: -180,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 39,
            category: 'redox',
            equation: 'Al + 3H+ = Al3+ + 1.5H2',
            displayEquation: 'Al + 3H<sup>+</sup> ⇌ Al<sup>3+</sup> + 1.5H<sub>2</sub>↑',
            name: '铝与酸反应',
            description: '金属铝的活动性',
            poeticDescription: '银镜反应，光华璀璨，醛基还原镜中生',
            reactants: ['Al', 'H+'],
            products: ['Al3+', 'H2'],
            coefficients: { 'Al': 1, 'H+': 3, 'Al3+': 1, 'H2': 1.5 },
            initialConcentrations: { 'Al': 1, 'H+': 1, 'Al3+': 0.1, 'H2': 0.1 },
            equilibriumConstant: 1e50,
            deltaH: -530,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2'],
            difficulty: 2
        },
        {
            id: 40,
            category: 'redox',
            equation: '3Cl2 + 6OH- = ClO3- + 5Cl- + 3H2O',
            displayEquation: '3Cl<sub>2</sub> + 6OH<sup>-</sup> ⇌ ClO<sub>3</sub><sup>-</sup> + 5Cl<sup>-</sup> + 3H<sub>2</sub>O',
            name: '氯气歧化',
            description: '氯气与碱的反应',
            poeticDescription: '费林试剂，砖红沉淀，糖类检验展真容',
            reactants: ['Cl2', 'OH-'],
            products: ['ClO3-', 'Cl-', 'H2O'],
            coefficients: { 'Cl2': 3, 'OH-': 6, 'ClO3-': 1, 'Cl-': 5, 'H2O': 3 },
            initialConcentrations: { 'Cl2': 0.4, 'OH-': 0.8, 'ClO3-': 0.05, 'Cl-': 0.2, 'H2O': 1 },
            equilibriumConstant: 1e25,
            deltaH: -220,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['Cl2'],
            difficulty: 4
        },

        // ===== 溶解平衡 (41-60) =====
        {
            id: 41,
            category: 'dissolution',
            equation: 'AgCl(s) = Ag+ + Cl-',
            displayEquation: 'AgCl(s) ⇌ Ag<sup>+</sup> + Cl<sup>-</sup>',
            name: '氯化银溶解',
            description: 'Ksp = 1.8×10^-10',
            poeticDescription: '难溶盐解，动态平衡，溶解沉淀两相生',
            reactants: ['AgCl'],
            products: ['Ag+', 'Cl-'],
            coefficients: { 'AgCl': 1, 'Ag+': 1, 'Cl-': 1 },
            initialConcentrations: { 'AgCl': 1, 'Ag+': 1e-5, 'Cl-': 1e-5 },
            equilibriumConstant: 1.8e-10,
            deltaH: 65,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 42,
            category: 'dissolution',
            equation: 'CaCO3(s) = Ca2+ + CO32-',
            displayEquation: 'CaCO<sub>3</sub>(s) ⇌ Ca<sup>2+</sup> + CO<sub>3</sub><sup>2-</sup>',
            name: '碳酸钙溶解',
            description: 'Ksp = 2.8×10^-9',
            poeticDescription: '氯化银溶，银离子游，溶度积小显本色',
            reactants: ['CaCO3'],
            products: ['Ca2+', 'CO32-'],
            coefficients: { 'CaCO3': 1, 'Ca2+': 1, 'CO32-': 1 },
            initialConcentrations: { 'CaCO3': 1, 'Ca2+': 5e-5, 'CO32-': 5e-5 },
            equilibriumConstant: 2.8e-9,
            deltaH: 13,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 43,
            category: 'dissolution',
            equation: 'BaSO4(s) = Ba2+ + SO42-',
            displayEquation: 'BaSO<sub>4</sub>(s) ⇌ Ba<sup>2+</sup> + SO<sub>4</sub><sup>2-</sup>',
            name: '硫酸钡溶解',
            description: 'Ksp = 1.1×10^-10',
            poeticDescription: '氢氧化镁，微溶于水，碱土金属半遮面',
            reactants: ['BaSO4'],
            products: ['Ba2+', 'SO42-'],
            coefficients: { 'BaSO4': 1, 'Ba2+': 1, 'SO42-': 1 },
            initialConcentrations: { 'BaSO4': 1, 'Ba2+': 1e-5, 'SO42-': 1e-5 },
            equilibriumConstant: 1.1e-10,
            deltaH: 20,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 44,
            category: 'dissolution',
            equation: 'Fe(OH)3(s) = Fe3+ + 3OH-',
            displayEquation: 'Fe(OH)<sub>3</sub>(s) ⇌ Fe<sup>3+</sup> + 3OH<sup>-</sup>',
            name: '氢氧化铁溶解',
            description: 'Ksp = 2.8×10^-39',
            poeticDescription: '硫酸钡固，不溶之王，钡餐造影藏玄机',
            reactants: ['Fe(OH)3'],
            products: ['Fe3+', 'OH-'],
            coefficients: { 'Fe(OH)3': 1, 'Fe3+': 1, 'OH-': 3 },
            initialConcentrations: { 'Fe(OH)3': 1, 'Fe3+': 1e-10, 'OH-': 1e-10 },
            equilibriumConstant: 2.8e-39,
            deltaH: 100,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 45,
            category: 'dissolution',
            equation: 'Mg(OH)2(s) = Mg2+ + 2OH-',
            displayEquation: 'Mg(OH)<sub>2</sub>(s) ⇌ Mg<sup>2+</sup> + 2OH<sup>-</sup>',
            name: '氢氧化镁溶解',
            description: 'Ksp = 5.6×10^-12',
            poeticDescription: '碳酸钙溶，酸雨侵蚀，石灰岩中见沧桑',
            reactants: ['Mg(OH)2'],
            products: ['Mg2+', 'OH-'],
            coefficients: { 'Mg(OH)2': 1, 'Mg2+': 1, 'OH-': 2 },
            initialConcentrations: { 'Mg(OH)2': 1, 'Mg2+': 1e-4, 'OH-': 2e-4 },
            equilibriumConstant: 5.6e-12,
            deltaH: 40,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 46,
            category: 'dissolution',
            equation: 'Cu(OH)2(s) = Cu2+ + 2OH-',
            displayEquation: 'Cu(OH)<sub>2</sub>(s) ⇌ Cu<sup>2+</sup> + 2OH<sup>-</sup>',
            name: '氢氧化铜溶解',
            description: 'Ksp = 2.2×10^-20',
            poeticDescription: '氟化钙弱，牙齿之基，微量溶解护齿康',
            reactants: ['Cu(OH)2'],
            products: ['Cu2+', 'OH-'],
            coefficients: { 'Cu(OH)2': 1, 'Cu2+': 1, 'OH-': 2 },
            initialConcentrations: { 'Cu(OH)2': 1, 'Cu2+': 1e-7, 'OH-': 2e-7 },
            equilibriumConstant: 2.2e-20,
            deltaH: 50,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 47,
            category: 'dissolution',
            equation: 'PbSO4(s) = Pb2+ + SO42-',
            displayEquation: 'PbSO<sub>4</sub>(s) ⇌ Pb<sup>2+</sup> + SO<sub>4</sub><sup>2-</sup>',
            name: '硫酸铅溶解',
            description: 'Ksp = 1.6×10^-8',
            poeticDescription: '磷酸钙固，骨骼铸成，生命之源固守坚',
            reactants: ['PbSO4'],
            products: ['Pb2+', 'SO42-'],
            coefficients: { 'PbSO4': 1, 'Pb2+': 1, 'SO42-': 1 },
            initialConcentrations: { 'PbSO4': 1, 'Pb2+': 1e-4, 'SO42-': 1e-4 },
            equilibriumConstant: 1.6e-8,
            deltaH: 25,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 48,
            category: 'dissolution',
            equation: 'Ag2CrO4(s) = 2Ag+ + CrO42-',
            displayEquation: 'Ag<sub>2</sub>CrO<sub>4</sub>(s) ⇌ 2Ag<sup>+</sup> + CrO<sub>4</sub><sup>2-</sup>',
            name: '铬酸银溶解',
            description: 'Ksp = 1.1×10^-12',
            poeticDescription: '硫化铜黑，不溶之质，沉淀转化显层级',
            reactants: ['Ag2CrO4'],
            products: ['Ag+', 'CrO42-'],
            coefficients: { 'Ag2CrO4': 1, 'Ag+': 2, 'CrO42-': 1 },
            initialConcentrations: { 'Ag2CrO4': 1, 'Ag+': 1e-4, 'CrO42-': 5e-5 },
            equilibriumConstant: 1.1e-12,
            deltaH: 70,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 49,
            category: 'dissolution',
            equation: 'PbCl2(s) = Pb2+ + 2Cl-',
            displayEquation: 'PbCl<sub>2</sub>(s) ⇌ Pb<sup>2+</sup> + 2Cl<sup>-</sup>',
            name: '氯化铅溶解',
            description: 'Ksp = 1.6×10^-5',
            poeticDescription: '氢氧化铁，胶体悬浮，纳米之间显奇观',
            reactants: ['PbCl2'],
            products: ['Pb2+', 'Cl-'],
            coefficients: { 'PbCl2': 1, 'Pb2+': 1, 'Cl-': 2 },
            initialConcentrations: { 'PbCl2': 1, 'Pb2+': 1e-2, 'Cl-': 2e-2 },
            equilibriumConstant: 1.6e-5,
            deltaH: 35,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 50,
            category: 'dissolution',
            equation: 'CaF2(s) = Ca2+ + 2F-',
            displayEquation: 'CaF<sub>2</sub>(s) ⇌ Ca<sup>2+</sup> + 2F<sup>-</sup>',
            name: '氟化钙溶解',
            description: 'Ksp = 3.9×10^-11',
            poeticDescription: '碘化银黄，感光之魂，卤化银族各有姿',
            reactants: ['CaF2'],
            products: ['Ca2+', 'F-'],
            coefficients: { 'CaF2': 1, 'Ca2+': 1, 'F-': 2 },
            initialConcentrations: { 'CaF2': 1, 'Ca2+': 2e-4, 'F-': 4e-4 },
            equilibriumConstant: 3.9e-11,
            deltaH: 18,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 51,
            category: 'dissolution',
            equation: 'ZnS(s) = Zn2+ + S2-',
            displayEquation: 'ZnS(s) ⇌ Zn<sup>2+</sup> + S<sup>2-</sup>',
            name: '硫化锌溶解',
            description: 'Ksp = 1.6×10^-24',
            poeticDescription: '硫酸钙半，石膏之源，建筑材料古今用',
            reactants: ['ZnS'],
            products: ['Zn2+', 'S2-'],
            coefficients: { 'ZnS': 1, 'Zn2+': 1, 'S2-': 1 },
            initialConcentrations: { 'ZnS': 1, 'Zn2+': 1e-12, 'S2-': 1e-12 },
            equilibriumConstant: 1.6e-24,
            deltaH: 20,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 52,
            category: 'dissolution',
            equation: 'CuS(s) = Cu2+ + S2-',
            displayEquation: 'CuS(s) ⇌ Cu<sup>2+</sup> + S<sup>2-</sup>',
            name: '硫化铜溶解',
            description: 'Ksp = 6.3×10^-36',
            poeticDescription: '草酸钙石，肾结晶痛，溶解平衡关健康',
            reactants: ['CuS'],
            products: ['Cu2+', 'S2-'],
            coefficients: { 'CuS': 1, 'Cu2+': 1, 'S2-': 1 },
            initialConcentrations: { 'CuS': 1, 'Cu2+': 1e-18, 'S2-': 1e-18 },
            equilibriumConstant: 6.3e-36,
            deltaH: 45,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 4
        },
        {
            id: 53,
            category: 'dissolution',
            equation: 'PbI2(s) = Pb2+ + 2I-',
            displayEquation: 'PbI<sub>2</sub>(s) ⇌ Pb<sup>2+</sup> + 2I<sup>-</sup>',
            name: '碘化铅溶解',
            description: 'Ksp = 7.1×10^-9',
            poeticDescription: '碳酸钡毒，可溶致命，钡盐化学需谨慎',
            reactants: ['PbI2'],
            products: ['Pb2+', 'I-'],
            coefficients: { 'PbI2': 1, 'Pb2+': 1, 'I-': 2 },
            initialConcentrations: { 'PbI2': 1, 'Pb2+': 1e-3, 'I-': 2e-3 },
            equilibriumConstant: 7.1e-9,
            deltaH: 30,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 54,
            category: 'dissolution',
            equation: 'Al(OH)3(s) = Al3+ + 3OH-',
            displayEquation: 'Al(OH)<sub>3</sub>(s) ⇌ Al<sup>3+</sup> + 3OH<sup>-</sup>',
            name: '氢氧化铝溶解',
            description: 'Ksp = 1.3×10^-33',
            poeticDescription: '硫化银黑，光敏弱者，卤化银中最沉默',
            reactants: ['Al(OH)3'],
            products: ['Al3+', 'OH-'],
            coefficients: { 'Al(OH)3': 1, 'Al3+': 1, 'OH-': 3 },
            initialConcentrations: { 'Al(OH)3': 1, 'Al3+': 1e-11, 'OH-': 3e-11 },
            equilibriumConstant: 1.3e-33,
            deltaH: 40,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 4
        },
        {
            id: 55,
            category: 'dissolution',
            equation: 'Ag3PO4(s) = 3Ag+ + PO43-',
            displayEquation: 'Ag<sub>3</sub>PO<sub>4</sub>(s) ⇌ 3Ag<sup>+</sup> + PO<sub>4</sub><sup>3-</sup>',
            name: '磷酸银溶解',
            description: 'Ksp = 2.8×10^-18',
            poeticDescription: '氢氧化铜，蓝色微溶，悬浮液中见天青',
            reactants: ['Ag3PO4'],
            products: ['Ag+', 'PO43-'],
            coefficients: { 'Ag3PO4': 1, 'Ag+': 3, 'PO43-': 1 },
            initialConcentrations: { 'Ag3PO4': 1, 'Ag+': 1e-5, 'PO43-': 3e-6 },
            equilibriumConstant: 2.8e-18,
            deltaH: 55,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 56,
            category: 'dissolution',
            equation: 'Fe(OH)2(s) = Fe2+ + 2OH-',
            displayEquation: 'Fe(OH)<sub>2</sub>(s) ⇌ Fe<sup>2+</sup> + 2OH<sup>-</sup>',
            name: '氢氧化亚铁溶解',
            description: 'Ksp = 8.0×10^-16',
            poeticDescription: '铬酸银砖，红色沉淀，指示剂中展锋芒',
            reactants: ['Fe(OH)2'],
            products: ['Fe2+', 'OH-'],
            coefficients: { 'Fe(OH)2': 1, 'Fe2+': 1, 'OH-': 2 },
            initialConcentrations: { 'Fe(OH)2': 1, 'Fe2+': 1e-5, 'OH-': 2e-5 },
            equilibriumConstant: 8.0e-16,
            deltaH: 35,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 57,
            category: 'dissolution',
            equation: 'BaCrO4(s) = Ba2+ + CrO42-',
            displayEquation: 'BaCrO<sub>4</sub>(s) ⇌ Ba<sup>2+</sup> + CrO<sub>4</sub><sup>2-</sup>',
            name: '铬酸钡溶解',
            description: 'Ksp = 1.2×10^-10',
            poeticDescription: '磷酸银黄，弱溶之质，银盐家族多姿态',
            reactants: ['BaCrO4'],
            products: ['Ba2+', 'CrO42-'],
            coefficients: { 'BaCrO4': 1, 'Ba2+': 1, 'CrO42-': 1 },
            initialConcentrations: { 'BaCrO4': 1, 'Ba2+': 1e-5, 'CrO42-': 1e-5 },
            equilibriumConstant: 1.2e-10,
            deltaH: 22,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 58,
            category: 'dissolution',
            equation: 'SrSO4(s) = Sr2+ + SO42-',
            displayEquation: 'SrSO<sub>4</sub>(s) ⇌ Sr<sup>2+</sup> + SO<sub>4</sub><sup>2-</sup>',
            name: '硫酸锶溶解',
            description: 'Ksp = 3.2×10^-7',
            poeticDescription: '硫酸银微，可溶银盐，溶解度表有差异',
            reactants: ['SrSO4'],
            products: ['Sr2+', 'SO42-'],
            coefficients: { 'SrSO4': 1, 'Sr2+': 1, 'SO42-': 1 },
            initialConcentrations: { 'SrSO4': 1, 'Sr2+': 5e-4, 'SO42-': 5e-4 },
            equilibriumConstant: 3.2e-7,
            deltaH: 28,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 59,
            category: 'dissolution',
            equation: 'Mn(OH)2(s) = Mn2+ + 2OH-',
            displayEquation: 'Mn(OH)<sub>2</sub>(s) ⇌ Mn<sup>2+</sup> + 2OH<sup>-</sup>',
            name: '氢氧化锰溶解',
            description: 'Ksp = 1.9×10^-13',
            poeticDescription: '碳酸锶白，焰色反应，红光闪耀在烟花',
            reactants: ['Mn(OH)2'],
            products: ['Mn2+', 'OH-'],
            coefficients: { 'Mn(OH)2': 1, 'Mn2+': 1, 'OH-': 2 },
            initialConcentrations: { 'Mn(OH)2': 1, 'Mn2+': 3e-5, 'OH-': 6e-5 },
            equilibriumConstant: 1.9e-13,
            deltaH: 33,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 60,
            category: 'dissolution',
            equation: 'CaSO4(s) = Ca2+ + SO42-',
            displayEquation: 'CaSO<sub>4</sub>(s) ⇌ Ca<sup>2+</sup> + SO<sub>4</sub><sup>2-</sup>',
            name: '硫酸钙溶解',
            description: 'Ksp = 2.4×10^-5',
            poeticDescription: '氯化铅白，热水可溶，温度对溶解显影响',
            reactants: ['CaSO4'],
            products: ['Ca2+', 'SO42-'],
            coefficients: { 'CaSO4': 1, 'Ca2+': 1, 'SO42-': 1 },
            initialConcentrations: { 'CaSO4': 1, 'Ca2+': 5e-3, 'SO42-': 5e-3 },
            equilibriumConstant: 2.4e-5,
            deltaH: 18,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },

        // ===== 电离水解 (61-80) =====
        {
            id: 61,
            category: 'ionization',
            equation: 'CH3COOH = CH3COO- + H+',
            displayEquation: 'CH<sub>3</sub>COOH ⇌ CH<sub>3</sub>COO<sup>-</sup> + H<sup>+</sup>',
            name: '醋酸电离',
            description: 'Ka = 1.8×10^-5',
            poeticDescription: '弱酸电离，部分解离，可逆平衡藏其中',
            reactants: ['CH3COOH'],
            products: ['CH3COO-', 'H+'],
            coefficients: { 'CH3COOH': 1, 'CH3COO-': 1, 'H+': 1 },
            initialConcentrations: { 'CH3COOH': 0.1, 'CH3COO-': 0.001, 'H+': 0.001 },
            equilibriumConstant: 1.8e-5,
            deltaH: -0.4,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 62,
            category: 'ionization',
            equation: 'NH3·H2O = NH4+ + OH-',
            displayEquation: 'NH<sub>3</sub>·H<sub>2</sub>O ⇌ NH<sub>4</sub><sup>+</sup> + OH<sup>-</sup>',
            name: '氨水电离',
            description: 'Kb = 1.8×10^-5',
            poeticDescription: '弱碱电离，氨水为例，离子浓度随温变',
            reactants: ['NH3·H2O'],
            products: ['NH4+', 'OH-'],
            coefficients: { 'NH3·H2O': 1, 'NH4+': 1, 'OH-': 1 },
            initialConcentrations: { 'NH3·H2O': 0.1, 'NH4+': 0.001, 'OH-': 0.001 },
            equilibriumConstant: 1.8e-5,
            deltaH: 35,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 63,
            category: 'ionization',
            equation: 'H2CO3 = HCO3- + H+',
            displayEquation: 'H<sub>2</sub>CO<sub>3</sub> ⇌ HCO<sub>3</sub><sup>-</sup> + H<sup>+</sup>',
            name: '碳酸一级电离',
            description: 'Ka1 = 4.3×10^-7',
            poeticDescription: '水的电离，中性之源，氢氧平衡天地正',
            reactants: ['H2CO3'],
            products: ['HCO3-', 'H+'],
            coefficients: { 'H2CO3': 1, 'HCO3-': 1, 'H+': 1 },
            initialConcentrations: { 'H2CO3': 0.1, 'HCO3-': 0.001, 'H+': 0.001 },
            equilibriumConstant: 4.3e-7,
            deltaH: 7,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 64,
            category: 'ionization',
            equation: 'HCO3- = CO32- + H+',
            displayEquation: 'HCO<sub>3</sub><sup>-</sup> ⇌ CO<sub>3</sub><sup>2-</sup> + H<sup>+</sup>',
            name: '碳酸二级电离',
            description: 'Ka2 = 5.6×10^-11',
            poeticDescription: '盐类水解，酸碱变化，离子反应定pH',
            reactants: ['HCO3-'],
            products: ['CO32-', 'H+'],
            coefficients: { 'HCO3-': 1, 'CO32-': 1, 'H+': 1 },
            initialConcentrations: { 'HCO3-': 0.1, 'CO32-': 0.0001, 'H+': 0.0001 },
            equilibriumConstant: 5.6e-11,
            deltaH: 15,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 65,
            category: 'ionization',
            equation: 'CH3COO- + H2O = CH3COOH + OH-',
            displayEquation: 'CH<sub>3</sub>COO<sup>-</sup> + H<sub>2</sub>O ⇌ CH<sub>3</sub>COOH + OH<sup>-</sup>',
            name: '醋酸根水解',
            description: '弱酸强碱盐水解',
            poeticDescription: '醋酸电离，部分解离，缓冲溶液显其能',
            reactants: ['CH3COO-', 'H2O'],
            products: ['CH3COOH', 'OH-'],
            coefficients: { 'CH3COO-': 1, 'H2O': 1, 'CH3COOH': 1, 'OH-': 1 },
            initialConcentrations: { 'CH3COO-': 0.1, 'H2O': 1, 'CH3COOH': 0.001, 'OH-': 0.001 },
            equilibriumConstant: 5.6e-10,
            deltaH: 50,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 66,
            category: 'ionization',
            equation: 'NH4+ + H2O = NH3·H2O + H+',
            displayEquation: 'NH<sub>4</sub><sup>+</sup> + H<sub>2</sub>O ⇌ NH<sub>3</sub>·H<sub>2</sub>O + H<sup>+</sup>',
            name: '铵根水解',
            description: '强酸弱碱盐水解',
            poeticDescription: '碳酸电离，两步进行，多元弱酸层层解',
            reactants: ['NH4+', 'H2O'],
            products: ['NH3·H2O', 'H+'],
            coefficients: { 'NH4+': 1, 'H2O': 1, 'NH3·H2O': 1, 'H+': 1 },
            initialConcentrations: { 'NH4+': 0.1, 'H2O': 1, 'NH3·H2O': 0.001, 'H+': 0.001 },
            equilibriumConstant: 5.6e-10,
            deltaH: 52,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 67,
            category: 'ionization',
            equation: 'H3PO4 = H2PO4- + H+',
            displayEquation: 'H<sub>3</sub>PO<sub>4</sub> ⇌ H<sub>2</sub>PO<sub>4</sub><sup>-</sup> + H<sup>+</sup>',
            name: '磷酸一级电离',
            description: 'Ka1 = 7.5×10^-3',
            poeticDescription: '磷酸电离，三步缓冲，生物体液稳态源',
            reactants: ['H3PO4'],
            products: ['H2PO4-', 'H+'],
            coefficients: { 'H3PO4': 1, 'H2PO4-': 1, 'H+': 1 },
            initialConcentrations: { 'H3PO4': 0.1, 'H2PO4-': 0.02, 'H+': 0.02 },
            equilibriumConstant: 7.5e-3,
            deltaH: 5,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 68,
            category: 'ionization',
            equation: 'H2PO4- = HPO42- + H+',
            displayEquation: 'H<sub>2</sub>PO<sub>4</sub><sup>-</sup> ⇌ HPO<sub>4</sub><sup>2-</sup> + H<sup>+</sup>',
            name: '磷酸二级电离',
            description: 'Ka2 = 6.2×10^-8',
            poeticDescription: '氨水电离，碱性微弱，氮肥之源农业魂',
            reactants: ['H2PO4-'],
            products: ['HPO42-', 'H+'],
            coefficients: { 'H2PO4-': 1, 'HPO42-': 1, 'H+': 1 },
            initialConcentrations: { 'H2PO4-': 0.1, 'HPO42-': 0.0008, 'H+': 0.0008 },
            equilibriumConstant: 6.2e-8,
            deltaH: 8,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 69,
            category: 'ionization',
            equation: 'HPO42- = PO43- + H+',
            displayEquation: 'HPO<sub>4</sub><sup>2-</sup> ⇌ PO<sub>4</sub><sup>3-</sup> + H<sup>+</sup>',
            name: '磷酸三级电离',
            description: 'Ka3 = 4.8×10^-13',
            poeticDescription: '铝盐水解，酸性显现，三价金属水解强',
            reactants: ['HPO42-'],
            products: ['PO43-', 'H+'],
            coefficients: { 'HPO42-': 1, 'PO43-': 1, 'H+': 1 },
            initialConcentrations: { 'HPO42-': 0.1, 'PO43-': 0.00002, 'H+': 0.00002 },
            equilibriumConstant: 4.8e-13,
            deltaH: 10,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 4
        },
        {
            id: 70,
            category: 'ionization',
            equation: 'H2S = HS- + H+',
            displayEquation: 'H<sub>2</sub>S ⇌ HS<sup>-</sup> + H<sup>+</sup>',
            name: '硫化氢一级电离',
            description: 'Ka1 = 9.1×10^-8',
            poeticDescription: '碳酸钠碱，水解显碱，强碱弱酸盐特性',
            reactants: ['H2S'],
            products: ['HS-', 'H+'],
            coefficients: { 'H2S': 1, 'HS-': 1, 'H+': 1 },
            initialConcentrations: { 'H2S': 0.1, 'HS-': 0.0003, 'H+': 0.0003 },
            equilibriumConstant: 9.1e-8,
            deltaH: 12,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 71,
            category: 'ionization',
            equation: 'HS- = S2- + H+',
            displayEquation: 'HS<sup>-</sup> ⇌ S<sup>2-</sup> + H<sup>+</sup>',
            name: '硫化氢二级电离',
            description: 'Ka2 = 1.2×10^-13',
            poeticDescription: '硫酸铝酸，双重水解，酸式铝盐pH低',
            reactants: ['HS-'],
            products: ['S2-', 'H+'],
            coefficients: { 'HS-': 1, 'S2-': 1, 'H+': 1 },
            initialConcentrations: { 'HS-': 0.1, 'S2-': 0.00001, 'H+': 0.00001 },
            equilibriumConstant: 1.2e-13,
            deltaH: 15,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 72,
            category: 'ionization',
            equation: 'HF = F- + H+',
            displayEquation: 'HF ⇌ F<sup>-</sup> + H<sup>+</sup>',
            name: '氢氟酸电离',
            description: 'Ka = 3.5×10^-4',
            poeticDescription: '氯化铁酸，水解显酸，混凝剂中展威能',
            reactants: ['HF'],
            products: ['F-', 'H+'],
            coefficients: { 'HF': 1, 'F-': 1, 'H+': 1 },
            initialConcentrations: { 'HF': 0.1, 'F-': 0.006, 'H+': 0.006 },
            equilibriumConstant: 3.5e-4,
            deltaH: -2,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 73,
            category: 'ionization',
            equation: 'HNO2 = NO2- + H+',
            displayEquation: 'HNO<sub>2</sub> ⇌ NO<sub>2</sub><sup>-</sup> + H<sup>+</sup>',
            name: '亚硝酸电离',
            description: 'Ka = 4.6×10^-4',
            poeticDescription: '醋酸钠碱，弱酸强碱，水解平衡向左行',
            reactants: ['HNO2'],
            products: ['NO2-', 'H+'],
            coefficients: { 'HNO2': 1, 'NO2-': 1, 'H+': 1 },
            initialConcentrations: { 'HNO2': 0.1, 'NO2-': 0.007, 'H+': 0.007 },
            equilibriumConstant: 4.6e-4,
            deltaH: 3,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 74,
            category: 'ionization',
            equation: 'HCOOH = HCOO- + H+',
            displayEquation: 'HCOOH ⇌ HCOO<sup>-</sup> + H<sup>+</sup>',
            name: '甲酸电离',
            description: 'Ka = 1.8×10^-4',
            poeticDescription: '碳酸氢钠，两性之质，既能受酸又受碱',
            reactants: ['HCOOH'],
            products: ['HCOO-', 'H+'],
            coefficients: { 'HCOOH': 1, 'HCOO-': 1, 'H+': 1 },
            initialConcentrations: { 'HCOOH': 0.1, 'HCOO-': 0.004, 'H+': 0.004 },
            equilibriumConstant: 1.8e-4,
            deltaH: 1,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 75,
            category: 'ionization',
            equation: 'H2SO3 = HSO3- + H+',
            displayEquation: 'H<sub>2</sub>SO<sub>3</sub> ⇌ HSO<sub>3</sub><sup>-</sup> + H<sup>+</sup>',
            name: '亚硫酸一级电离',
            description: 'Ka1 = 1.5×10^-2',
            poeticDescription: '磷酸氢盐，缓冲体系，生理pH稳如山',
            reactants: ['H2SO3'],
            products: ['HSO3-', 'H+'],
            coefficients: { 'H2SO3': 1, 'HSO3-': 1, 'H+': 1 },
            initialConcentrations: { 'H2SO3': 0.1, 'HSO3-': 0.03, 'H+': 0.03 },
            equilibriumConstant: 1.5e-2,
            deltaH: 6,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 76,
            category: 'ionization',
            equation: 'CO32- + H2O = HCO3- + OH-',
            displayEquation: 'CO<sub>3</sub><sup>2-</sup> + H<sub>2</sub>O ⇌ HCO<sub>3</sub><sup>-</sup> + OH<sup>-</sup>',
            name: '碳酸根水解',
            description: '强碱弱酸盐水解',
            poeticDescription: '硫化钠碱，强碱弱酸，水解程度较显著',
            reactants: ['CO32-', 'H2O'],
            products: ['HCO3-', 'OH-'],
            coefficients: { 'CO32-': 1, 'H2O': 1, 'HCO3-': 1, 'OH-': 1 },
            initialConcentrations: { 'CO32-': 0.1, 'H2O': 1, 'HCO3-': 0.002, 'OH-': 0.002 },
            equilibriumConstant: 1.8e-4,
            deltaH: 55,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 77,
            category: 'ionization',
            equation: 'PO43- + H2O = HPO42- + OH-',
            displayEquation: 'PO<sub>4</sub><sup>3-</sup> + H<sub>2</sub>O ⇌ HPO<sub>4</sub><sup>2-</sup> + OH<sup>-</sup>',
            name: '磷酸根水解',
            description: '强碱性盐水解',
            poeticDescription: '氰化钠碱，剧毒之盐，弱酸根离水解强',
            reactants: ['PO43-', 'H2O'],
            products: ['HPO42-', 'OH-'],
            coefficients: { 'PO43-': 1, 'H2O': 1, 'HPO42-': 1, 'OH-': 1 },
            initialConcentrations: { 'PO43-': 0.1, 'H2O': 1, 'HPO42-': 0.02, 'OH-': 0.02 },
            equilibriumConstant: 2.1e-2,
            deltaH: 60,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 78,
            category: 'ionization',
            equation: 'F- + H2O = HF + OH-',
            displayEquation: 'F<sup>-</sup> + H<sub>2</sub>O ⇌ HF + OH<sup>-</sup>',
            name: '氟离子水解',
            description: '弱酸阴离子水解',
            poeticDescription: '硫酸铜酸，弱碱强酸，金属离子水解生',
            reactants: ['F-', 'H2O'],
            products: ['HF', 'OH-'],
            coefficients: { 'F-': 1, 'H2O': 1, 'HF': 1, 'OH-': 1 },
            initialConcentrations: { 'F-': 0.1, 'H2O': 1, 'HF': 0.002, 'OH-': 0.002 },
            equilibriumConstant: 2.9e-11,
            deltaH: 45,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 79,
            category: 'ionization',
            equation: 'CN- + H2O = HCN + OH-',
            displayEquation: 'CN<sup>-</sup> + H<sub>2</sub>O ⇌ HCN + OH<sup>-</sup>',
            name: '氰根水解',
            description: '极弱酸盐水解',
            poeticDescription: '氯化铵酸，弱碱强酸，铵根水解显酸性',
            reactants: ['CN-', 'H2O'],
            products: ['HCN', 'OH-'],
            coefficients: { 'CN-': 1, 'H2O': 1, 'HCN': 1, 'OH-': 1 },
            initialConcentrations: { 'CN-': 0.1, 'H2O': 1, 'HCN': 0.005, 'OH-': 0.005 },
            equilibriumConstant: 1.6e-5,
            deltaH: 50,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 80,
            category: 'ionization',
            equation: 'Al3+ + 3H2O = Al(OH)3 + 3H+',
            displayEquation: 'Al<sup>3+</sup> + 3H<sub>2</sub>O ⇌ Al(OH)<sub>3</sub> + 3H<sup>+</sup>',
            name: '铝离子水解',
            description: '高价金属离子水解',
            poeticDescription: '碳酸铵碱，双重水解，相互促进平衡移',
            reactants: ['Al3+', 'H2O'],
            products: ['Al(OH)3', 'H+'],
            coefficients: { 'Al3+': 1, 'H2O': 3, 'Al(OH)3': 1, 'H+': 3 },
            initialConcentrations: { 'Al3+': 0.1, 'H2O': 1, 'Al(OH)3': 0.001, 'H+': 0.003 },
            equilibriumConstant: 1.4e-15,
            deltaH: 70,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 4
        },

        // ===== 综合反应 (81-100) =====
        {
            id: 81,
            category: 'complex',
            equation: 'N2 + 3H2 = 2NH3',
            displayEquation: 'N<sub>2</sub> + 3H<sub>2</sub> ⇌ 2NH<sub>3</sub>',
            name: '合成氨',
            description: '哈伯法工业合成氨',
            poeticDescription: '合成氨式，工业之魂，哈伯催化养天下',
            reactants: ['N2', 'H2'],
            products: ['NH3'],
            coefficients: { 'N2': 1, 'H2': 3, 'NH3': 2 },
            initialConcentrations: { 'N2': 1, 'H2': 3, 'NH3': 0.1 },
            equilibriumConstant: 0.5,
            deltaH: -92,
            initialTemp: 723,
            initialPressure: 200,
            hasGas: true,
            gasSpecies: ['N2', 'H2', 'NH3'],
            difficulty: 3
        },
        {
            id: 82,
            category: 'complex',
            equation: '2SO2 + O2 = 2SO3',
            displayEquation: '2SO<sub>2</sub> + O<sub>2</sub> ⇌ 2SO<sub>3</sub>',
            name: '二氧化硫氧化',
            description: '接触法制硫酸',
            poeticDescription: '接触法制，硫酸为王，工业母液泽万物',
            reactants: ['SO2', 'O2'],
            products: ['SO3'],
            coefficients: { 'SO2': 2, 'O2': 1, 'SO3': 2 },
            initialConcentrations: { 'SO2': 0.5, 'O2': 0.5, 'SO3': 0.1 },
            equilibriumConstant: 5e5,
            deltaH: -198,
            initialTemp: 673,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['SO2', 'O2', 'SO3'],
            difficulty: 3
        },
        {
            id: 83,
            category: 'complex',
            equation: 'CO + H2O = CO2 + H2',
            displayEquation: 'CO + H<sub>2</sub>O ⇌ CO<sub>2</sub> + H<sub>2</sub>',
            name: '水煤气变换',
            description: '制取氢气',
            poeticDescription: '氯碱工业，电解食盐，碱氯氢气三分立',
            reactants: ['CO', 'H2O'],
            products: ['CO2', 'H2'],
            coefficients: { 'CO': 1, 'H2O': 1, 'CO2': 1, 'H2': 1 },
            initialConcentrations: { 'CO': 0.5, 'H2O': 0.5, 'CO2': 0.1, 'H2': 0.1 },
            equilibriumConstant: 1.0,
            deltaH: -41,
            initialTemp: 673,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO', 'H2O', 'CO2', 'H2'],
            difficulty: 3
        },
        {
            id: 84,
            category: 'complex',
            equation: 'PCl5 = PCl3 + Cl2',
            displayEquation: 'PCl<sub>5</sub> ⇌ PCl<sub>3</sub> + Cl<sub>2</sub>',
            name: '五氯化磷分解',
            description: '气相分解平衡',
            poeticDescription: '氨氧化法，硝酸之源，奥氏催化展神威',
            reactants: ['PCl5'],
            products: ['PCl3', 'Cl2'],
            coefficients: { 'PCl5': 1, 'PCl3': 1, 'Cl2': 1 },
            initialConcentrations: { 'PCl5': 0.5, 'PCl3': 0.1, 'Cl2': 0.1 },
            equilibriumConstant: 0.04,
            deltaH: 93,
            initialTemp: 523,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['PCl5', 'PCl3', 'Cl2'],
            difficulty: 3
        },
        {
            id: 85,
            category: 'complex',
            equation: '2NO2 = N2O4',
            displayEquation: '2NO<sub>2</sub> ⇌ N<sub>2</sub>O<sub>4</sub>',
            name: '二氧化氮二聚',
            description: '颜色变化平衡',
            poeticDescription: '甲醇合成，碳氢氧聚，清洁能源新时代',
            reactants: ['NO2'],
            products: ['N2O4'],
            coefficients: { 'NO2': 2, 'N2O4': 1 },
            initialConcentrations: { 'NO2': 0.5, 'N2O4': 0.1 },
            equilibriumConstant: 6.8,
            deltaH: -57,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['NO2', 'N2O4'],
            difficulty: 2
        },
        {
            id: 86,
            category: 'complex',
            equation: 'H2 + I2 = 2HI',
            displayEquation: 'H<sub>2</sub> + I<sub>2</sub> ⇌ 2HI',
            name: '碘化氢合成',
            description: '经典气相平衡',
            poeticDescription: '二氧化碳，甲醇转化，碳中和中见希望',
            reactants: ['H2', 'I2'],
            products: ['HI'],
            coefficients: { 'H2': 1, 'I2': 1, 'HI': 2 },
            initialConcentrations: { 'H2': 0.5, 'I2': 0.5, 'HI': 0.1 },
            equilibriumConstant: 50,
            deltaH: -10,
            initialTemp: 698,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2', 'I2', 'HI'],
            difficulty: 2
        },
        {
            id: 87,
            category: 'complex',
            equation: 'C + CO2 = 2CO',
            displayEquation: 'C + CO<sub>2</sub> ⇌ 2CO',
            name: '碳还原二氧化碳',
            description: '布多尔反应',
            poeticDescription: '乙烯氧化，环氧乙烷，有机合成起点站',
            reactants: ['C', 'CO2'],
            products: ['CO'],
            coefficients: { 'C': 1, 'CO2': 1, 'CO': 2 },
            initialConcentrations: { 'C': 1, 'CO2': 0.5, 'CO': 0.1 },
            equilibriumConstant: 1e-3,
            deltaH: 172,
            initialTemp: 1000,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO2', 'CO'],
            difficulty: 3
        },
        {
            id: 88,
            category: 'complex',
            equation: 'CH4 + H2O = CO + 3H2',
            displayEquation: 'CH<sub>4</sub> + H<sub>2</sub>O ⇌ CO + 3H<sub>2</sub>',
            name: '甲烷蒸汽重整',
            description: '工业制氢',
            poeticDescription: '苯乙烯聚，塑料之源，高分子链长如绳',
            reactants: ['CH4', 'H2O'],
            products: ['CO', 'H2'],
            coefficients: { 'CH4': 1, 'H2O': 1, 'CO': 1, 'H2': 3 },
            initialConcentrations: { 'CH4': 0.5, 'H2O': 0.5, 'CO': 0.1, 'H2': 0.3 },
            equilibriumConstant: 2e-4,
            deltaH: 206,
            initialTemp: 1073,
            initialPressure: 200,
            hasGas: true,
            gasSpecies: ['CH4', 'H2O', 'CO', 'H2'],
            difficulty: 4
        },
        {
            id: 89,
            category: 'complex',
            equation: 'CaCO3 = CaO + CO2',
            displayEquation: 'CaCO<sub>3</sub> ⇌ CaO + CO<sub>2</sub>',
            name: '碳酸钙分解',
            description: '石灰石煅烧',
            poeticDescription: '酯化反应，香气四溢，有机合成展画廊',
            reactants: ['CaCO3'],
            products: ['CaO', 'CO2'],
            coefficients: { 'CaCO3': 1, 'CaO': 1, 'CO2': 1 },
            initialConcentrations: { 'CaCO3': 1, 'CaO': 0.1, 'CO2': 0.1 },
            equilibriumConstant: 0.04,
            deltaH: 178,
            initialTemp: 1100,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO2'],
            difficulty: 2
        },
        {
            id: 90,
            category: 'complex',
            equation: 'Fe2O3 + 3CO = 2Fe + 3CO2',
            displayEquation: 'Fe<sub>2</sub>O<sub>3</sub> + 3CO ⇌ 2Fe + 3CO<sub>2</sub>',
            name: '炼铁反应',
            description: '高炉炼铁',
            poeticDescription: '皂化反应，碱解脂肪，日用化学源于此',
            reactants: ['Fe2O3', 'CO'],
            products: ['Fe', 'CO2'],
            coefficients: { 'Fe2O3': 1, 'CO': 3, 'Fe': 2, 'CO2': 3 },
            initialConcentrations: { 'Fe2O3': 1, 'CO': 0.5, 'Fe': 0.1, 'CO2': 0.1 },
            equilibriumConstant: 100,
            deltaH: -25,
            initialTemp: 1200,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO', 'CO2'],
            difficulty: 3
        },
        {
            id: 91,
            category: 'complex',
            equation: '2C2H2 = C4H4',
            displayEquation: '2C<sub>2</sub>H<sub>2</sub> ⇌ C<sub>4</sub>H<sub>4</sub>',
            name: '乙炔二聚',
            description: '有机聚合反应',
            poeticDescription: '硝化反应，炸药之源，有机硝化威力大',
            reactants: ['C2H2'],
            products: ['C4H4'],
            coefficients: { 'C2H2': 2, 'C4H4': 1 },
            initialConcentrations: { 'C2H2': 0.5, 'C4H4': 0.1 },
            equilibriumConstant: 2.5,
            deltaH: -60,
            initialTemp: 873,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['C2H2', 'C4H4'],
            difficulty: 3
        },
        {
            id: 92,
            category: 'complex',
            equation: 'C2H4 + H2O = C2H5OH',
            displayEquation: 'C<sub>2</sub>H<sub>4</sub> + H<sub>2</sub>O ⇌ C<sub>2</sub>H<sub>5</sub>OH',
            name: '乙烯水合',
            description: '工业制乙醇',
            poeticDescription: '卤代反应，取代轮回，有机合成多路径',
            reactants: ['C2H4', 'H2O'],
            products: ['C2H5OH'],
            coefficients: { 'C2H4': 1, 'H2O': 1, 'C2H5OH': 1 },
            initialConcentrations: { 'C2H4': 0.5, 'H2O': 0.5, 'C2H5OH': 0.1 },
            equilibriumConstant: 0.8,
            deltaH: -45,
            initialTemp: 573,
            initialPressure: 300,
            hasGas: true,
            gasSpecies: ['C2H4'],
            difficulty: 3
        },
        {
            id: 93,
            category: 'complex',
            equation: '2C6H6 = C12H10 + H2',
            displayEquation: '2C<sub>6</sub>H<sub>6</sub> ⇌ C<sub>12</sub>H<sub>10</sub> + H<sub>2</sub>',
            name: '苯二聚脱氢',
            description: '芳香族聚合（简化）',
            poeticDescription: '加成反应，双键开裂，不饱和化合物质变',
            reactants: ['C6H6'],
            products: ['C12H10', 'H2'],
            coefficients: { 'C6H6': 2, 'C12H10': 1, 'H2': 1 },
            initialConcentrations: { 'C6H6': 0.6, 'C12H10': 0.05, 'H2': 0.1 },
            equilibriumConstant: 0.1,
            deltaH: 85,
            initialTemp: 973,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2'],
            difficulty: 4
        },
        {
            id: 94,
            category: 'complex',
            equation: 'CO2 + 3H2 = CH3OH + H2O',
            displayEquation: 'CO<sub>2</sub> + 3H<sub>2</sub> ⇌ CH<sub>3</sub>OH + H<sub>2</sub>O',
            name: '二氧化碳制甲醇',
            description: '绿色甲醇合成',
            poeticDescription: '消去反应，双键再生，醇类转化展锋芒',
            reactants: ['CO2', 'H2'],
            products: ['CH3OH', 'H2O'],
            coefficients: { 'CO2': 1, 'H2': 3, 'CH3OH': 1, 'H2O': 1 },
            initialConcentrations: { 'CO2': 0.5, 'H2': 1, 'CH3OH': 0.1, 'H2O': 0.2 },
            equilibriumConstant: 0.05,
            deltaH: -49,
            initialTemp: 523,
            initialPressure: 500,
            hasGas: true,
            gasSpecies: ['CO2', 'H2'],
            difficulty: 4
        },
        {
            id: 95,
            category: 'complex',
            equation: 'C2H5OH = C2H4 + H2O',
            displayEquation: 'C<sub>2</sub>H<sub>5</sub>OH ⇌ C<sub>2</sub>H<sub>4</sub> + H<sub>2</sub>O',
            name: '乙醇脱水',
            description: '制取乙烯',
            poeticDescription: '氧化还原，醇醛转化，有机化学层层进',
            reactants: ['C2H5OH'],
            products: ['C2H4', 'H2O'],
            coefficients: { 'C2H5OH': 1, 'C2H4': 1, 'H2O': 1 },
            initialConcentrations: { 'C2H5OH': 0.5, 'C2H4': 0.1, 'H2O': 0.2 },
            equilibriumConstant: 1.2,
            deltaH: 45,
            initialTemp: 443,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['C2H4'],
            difficulty: 3
        },
        {
            id: 96,
            category: 'complex',
            equation: 'CO + 2H2 = CH3OH',
            displayEquation: 'CO + 2H<sub>2</sub> ⇌ CH<sub>3</sub>OH',
            name: '甲醇合成',
            description: '工业合成甲醇',
            poeticDescription: '还原反应，羰基变醇，化学转化逆向行',
            reactants: ['CO', 'H2'],
            products: ['CH3OH'],
            coefficients: { 'CO': 1, 'H2': 2, 'CH3OH': 1 },
            initialConcentrations: { 'CO': 0.5, 'H2': 1, 'CH3OH': 0.1 },
            equilibriumConstant: 0.15,
            deltaH: -91,
            initialTemp: 523,
            initialPressure: 500,
            hasGas: true,
            gasSpecies: ['CO', 'H2'],
            difficulty: 3
        },
        {
            id: 97,
            category: 'complex',
            equation: 'N2O4 = 2NO2',
            displayEquation: 'N<sub>2</sub>O<sub>4</sub> ⇌ 2NO<sub>2</sub>',
            name: '四氧化二氮解离',
            description: '逆向二聚反应',
            poeticDescription: '缩聚反应，酯键生成，聚酯纤维长链结',
            reactants: ['N2O4'],
            products: ['NO2'],
            coefficients: { 'N2O4': 1, 'NO2': 2 },
            initialConcentrations: { 'N2O4': 0.5, 'NO2': 0.2 },
            equilibriumConstant: 0.147,
            deltaH: 57,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['N2O4', 'NO2'],
            difficulty: 2
        },
        {
            id: 98,
            category: 'complex',
            equation: 'C + H2O = CO + H2',
            displayEquation: 'C + H<sub>2</sub>O ⇌ CO + H<sub>2</sub>',
            name: '水煤气反应',
            description: '制取水煤气',
            poeticDescription: '加聚反应，单体相连，塑料世界由此生',
            reactants: ['C', 'H2O'],
            products: ['CO', 'H2'],
            coefficients: { 'C': 1, 'H2O': 1, 'CO': 1, 'H2': 1 },
            initialConcentrations: { 'C': 1, 'H2O': 0.5, 'CO': 0.1, 'H2': 0.1 },
            equilibriumConstant: 0.002,
            deltaH: 131,
            initialTemp: 1273,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2O', 'CO', 'H2'],
            difficulty: 3
        },
        {
            id: 99,
            category: 'complex',
            equation: '2CO = CO2 + C',
            displayEquation: '2CO ⇌ CO<sub>2</sub> + C',
            name: '一氧化碳歧化',
            description: '贝尔-杜萨反应',
            poeticDescription: '水解反应，酯键断裂，逆向平衡显其能',
            reactants: ['CO'],
            products: ['CO2', 'C'],
            coefficients: { 'CO': 2, 'CO2': 1, 'C': 1 },
            initialConcentrations: { 'CO': 0.6, 'CO2': 0.1, 'C': 0.1 },
            equilibriumConstant: 1e4,
            deltaH: -172,
            initialTemp: 900,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO', 'CO2'],
            difficulty: 3
        },
        {
            id: 100,
            category: 'complex',
            equation: '2H2S + SO2 = 3S + 2H2O',
            displayEquation: '2H<sub>2</sub>S + SO<sub>2</sub> ⇌ 3S + 2H<sub>2</sub>O',
            name: '克劳斯法脱硫',
            description: '硫磺回收工艺',
            poeticDescription: '催化氢化，加氢反应，石油化工展神威',
            reactants: ['H2S', 'SO2'],
            products: ['S', 'H2O'],
            coefficients: { 'H2S': 2, 'SO2': 1, 'S': 3, 'H2O': 2 },
            initialConcentrations: { 'H2S': 0.5, 'SO2': 0.3, 'S': 0.1, 'H2O': 0.2 },
            equilibriumConstant: 1e15,
            deltaH: -145,
            initialTemp: 573,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2S', 'SO2'],
            difficulty: 4
        },

        // ===== 电化学 (101-110) =====
        {
            id: 101,
            category: 'electrochemistry',
            equation: 'Zn + Cu2+ = Zn2+ + Cu',
            displayEquation: 'Zn + Cu<sup>2+</sup> ⇌ Zn<sup>2+</sup> + Cu',
            name: '铜锌原电池基础',
            description: '丹尼尔电池反应',
            poeticDescription: '原电池中，化学生电，氧化还原成动力',
            reactants: ['Zn', 'Cu2+'],
            products: ['Zn2+', 'Cu'],
            coefficients: { 'Zn': 1, 'Cu2+': 1, 'Zn2+': 1, 'Cu': 1 },
            initialConcentrations: { 'Zn': 1, 'Cu2+': 0.5, 'Zn2+': 0.1, 'Cu': 0.1 },
            equilibriumConstant: 1e37,
            deltaH: -210,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 102,
            category: 'electrochemistry',
            equation: '2H2O = 2H2 + O2',
            displayEquation: '2H<sub>2</sub>O ⇌ 2H<sub>2</sub>↑ + O<sub>2</sub>↑',
            name: '水的电解',
            description: '电解水反应',
            poeticDescription: '锌铜原电，伏打之源，电流涌动启文明',
            reactants: ['H2O'],
            products: ['H2', 'O2'],
            coefficients: { 'H2O': 2, 'H2': 2, 'O2': 1 },
            initialConcentrations: { 'H2O': 1, 'H2': 0.1, 'O2': 0.05 },
            equilibriumConstant: 1e-80,
            deltaH: 572,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2', 'O2'],
            difficulty: 2
        },
        {
            id: 103,
            category: 'electrochemistry',
            equation: '2Cl- = Cl2 + 2e-',
            displayEquation: '2Cl<sup>-</sup> ⇌ Cl<sub>2</sub>↑ + 2e<sup>-</sup> (简化)',
            name: '氯离子放电',
            description: '电解氯化钠溶液（简化）',
            poeticDescription: '燃料电池，清洁能源，氢氧反应生电能',
            reactants: ['Cl-'],
            products: ['Cl2'],
            coefficients: { 'Cl-': 2, 'Cl2': 1 },
            initialConcentrations: { 'Cl-': 1, 'Cl2': 0.1 },
            equilibriumConstant: 1e-30,
            deltaH: 240,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['Cl2'],
            difficulty: 3
        },
        {
            id: 104,
            category: 'electrochemistry',
            equation: 'Fe + 2H+ = Fe2+ + H2',
            displayEquation: 'Fe + 2H<sup>+</sup> ⇌ Fe<sup>2+</sup> + H<sub>2</sub>↑',
            name: '铁碳原电池',
            description: '钢铁腐蚀反应',
            poeticDescription: '电解食盐，氯碱工业，阴阳两极各有产',
            reactants: ['Fe', 'H+'],
            products: ['Fe2+', 'H2'],
            coefficients: { 'Fe': 1, 'H+': 2, 'Fe2+': 1, 'H2': 1 },
            initialConcentrations: { 'Fe': 1, 'H+': 0.8, 'Fe2+': 0.1, 'H2': 0.1 },
            equilibriumConstant: 1e28,
            deltaH: -85,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['H2'],
            difficulty: 2
        },
        {
            id: 105,
            category: 'electrochemistry',
            equation: 'Pb + PbO2 + 2H2SO4 = 2PbSO4 + 2H2O',
            displayEquation: 'Pb + PbO<sub>2</sub> + 2H<sub>2</sub>SO<sub>4</sub> ⇌ 2PbSO<sub>4</sub> + 2H<sub>2</sub>O',
            name: '铅蓄电池反应',
            description: '铅酸电池充放电',
            poeticDescription: '电镀铜层，表面防护，电化沉积展精妙',
            reactants: ['Pb', 'PbO2', 'H2SO4'],
            products: ['PbSO4', 'H2O'],
            coefficients: { 'Pb': 1, 'PbO2': 1, 'H2SO4': 2, 'PbSO4': 2, 'H2O': 2 },
            initialConcentrations: { 'Pb': 1, 'PbO2': 1, 'H2SO4': 0.8, 'PbSO4': 0.2, 'H2O': 1 },
            equilibriumConstant: 1e50,
            deltaH: -360,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 106,
            category: 'electrochemistry',
            equation: 'Li+ + e- = Li',
            displayEquation: 'Li<sup>+</sup> + e<sup>-</sup> ⇌ Li (简化)',
            name: '锂离子电池反应',
            description: '锂电池充电过程（简化）',
            poeticDescription: '电解水时，氢氧分离，电能转化显其能',
            reactants: ['Li+'],
            products: ['Li'],
            coefficients: { 'Li+': 1, 'Li': 1 },
            initialConcentrations: { 'Li+': 0.5, 'Li': 0.1 },
            equilibriumConstant: 1e-50,
            deltaH: 160,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 107,
            category: 'electrochemistry',
            equation: '4Fe(OH)2 + O2 + 2H2O = 4Fe(OH)3',
            displayEquation: '4Fe(OH)<sub>2</sub> + O<sub>2</sub> + 2H<sub>2</sub>O ⇌ 4Fe(OH)<sub>3</sub>',
            name: '吸氧腐蚀',
            description: '钢铁在中性环境腐蚀',
            poeticDescription: '铝的电解，冰晶石熔，工业制铝展雄威',
            reactants: ['Fe(OH)2', 'O2', 'H2O'],
            products: ['Fe(OH)3'],
            coefficients: { 'Fe(OH)2': 4, 'O2': 1, 'H2O': 2, 'Fe(OH)3': 4 },
            initialConcentrations: { 'Fe(OH)2': 0.5, 'O2': 0.2, 'H2O': 1, 'Fe(OH)3': 0.1 },
            equilibriumConstant: 1e40,
            deltaH: -320,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['O2'],
            difficulty: 3
        },
        {
            id: 108,
            category: 'electrochemistry',
            equation: '2Na+ + 2e- = 2Na',
            displayEquation: '2Na<sup>+</sup> + 2e<sup>-</sup> ⇌ 2Na (简化)',
            name: '钠的电解',
            description: '熔融盐电解',
            poeticDescription: '钢铁防腐，牺牲阳极，电化保护守长安',
            reactants: ['Na+'],
            products: ['Na'],
            coefficients: { 'Na+': 2, 'Na': 2 },
            initialConcentrations: { 'Na+': 1, 'Na': 0.05 },
            equilibriumConstant: 1e-70,
            deltaH: 220,
            initialTemp: 873,
            initialPressure: 101,
            hasGas: false,
            difficulty: 4
        },
        {
            id: 109,
            category: 'electrochemistry',
            equation: 'Cu2+ + 2e- = Cu',
            displayEquation: 'Cu<sup>2+</sup> + 2e<sup>-</sup> ⇌ Cu (简化)',
            name: '铜的电镀',
            description: '电解精炼铜',
            poeticDescription: '蓄电池中，充放轮回，化学电能互转化',
            reactants: ['Cu2+'],
            products: ['Cu'],
            coefficients: { 'Cu2+': 1, 'Cu': 1 },
            initialConcentrations: { 'Cu2+': 0.5, 'Cu': 0.1 },
            equilibriumConstant: 1e-20,
            deltaH: 65,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 110,
            category: 'electrochemistry',
            equation: 'Al2O3 = 2Al + 1.5O2',
            displayEquation: 'Al<sub>2</sub>O<sub>3</sub> ⇌ 2Al + 1.5O<sub>2</sub>',
            name: '铝的电解',
            description: '霍尔-埃鲁法炼铝',
            poeticDescription: '金属腐蚀，电化过程，原电池效应显破坏',
            reactants: ['Al2O3'],
            products: ['Al', 'O2'],
            coefficients: { 'Al2O3': 1, 'Al': 2, 'O2': 1.5 },
            initialConcentrations: { 'Al2O3': 1, 'Al': 0.1, 'O2': 0.1 },
            equilibriumConstant: 1e-100,
            deltaH: 1676,
            initialTemp: 1233,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['O2'],
            difficulty: 4
        },

        // ===== 有机反应 (111-120) =====
        {
            id: 111,
            category: 'organic',
            equation: 'CH3COOH + C2H5OH = CH3COOC2H5 + H2O',
            displayEquation: 'CH<sub>3</sub>COOH + C<sub>2</sub>H<sub>5</sub>OH ⇌ CH<sub>3</sub>COOC<sub>2</sub>H<sub>5</sub> + H<sub>2</sub>O',
            name: '酯化反应',
            description: '乙酸乙酯的合成',
            poeticDescription: '乙烯加水，乙醇生成，工业酒精源于此',
            reactants: ['CH3COOH', 'C2H5OH'],
            products: ['CH3COOC2H5', 'H2O'],
            coefficients: { 'CH3COOH': 1, 'C2H5OH': 1, 'CH3COOC2H5': 1, 'H2O': 1 },
            initialConcentrations: { 'CH3COOH': 0.5, 'C2H5OH': 0.5, 'CH3COOC2H5': 0.1, 'H2O': 0.2 },
            equilibriumConstant: 4.0,
            deltaH: -10,
            initialTemp: 333,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 112,
            category: 'organic',
            equation: 'CH3COOC2H5 + H2O = CH3COOH + C2H5OH',
            displayEquation: 'CH<sub>3</sub>COOC<sub>2</sub>H<sub>5</sub> + H<sub>2</sub>O ⇌ CH<sub>3</sub>COOH + C<sub>2</sub>H<sub>5</sub>OH',
            name: '酯水解',
            description: '乙酸乙酯的水解',
            poeticDescription: '乙醇氧化，乙醛转化，醇类化学展层级',
            reactants: ['CH3COOC2H5', 'H2O'],
            products: ['CH3COOH', 'C2H5OH'],
            coefficients: { 'CH3COOC2H5': 1, 'H2O': 1, 'CH3COOH': 1, 'C2H5OH': 1 },
            initialConcentrations: { 'CH3COOC2H5': 0.5, 'H2O': 1, 'CH3COOH': 0.1, 'C2H5OH': 0.1 },
            equilibriumConstant: 0.25,
            deltaH: 10,
            initialTemp: 333,
            initialPressure: 101,
            hasGas: false,
            difficulty: 2
        },
        {
            id: 113,
            category: 'organic',
            equation: 'C2H4 + H2 = C2H6',
            displayEquation: 'C<sub>2</sub>H<sub>4</sub> + H<sub>2</sub> ⇌ C<sub>2</sub>H<sub>6</sub>',
            name: '乙烯加氢',
            description: '烯烃还原反应',
            poeticDescription: '乙醛氧化，乙酸终产，羧酸之路层层进',
            reactants: ['C2H4', 'H2'],
            products: ['C2H6'],
            coefficients: { 'C2H4': 1, 'H2': 1, 'C2H6': 1 },
            initialConcentrations: { 'C2H4': 0.5, 'H2': 0.5, 'C2H6': 0.1 },
            equilibriumConstant: 1e15,
            deltaH: -137,
            initialTemp: 373,
            initialPressure: 300,
            hasGas: true,
            gasSpecies: ['C2H4', 'H2', 'C2H6'],
            difficulty: 2
        },
        {
            id: 114,
            category: 'organic',
            equation: 'C2H2 + H2O = CH3CHO',
            displayEquation: 'C<sub>2</sub>H<sub>2</sub> + H<sub>2</sub>O ⇌ CH<sub>3</sub>CHO',
            name: '乙炔水合',
            description: '制乙醛反应',
            poeticDescription: '酯化反应，芳香四溢，乙酸乙酯果香浓',
            reactants: ['C2H2', 'H2O'],
            products: ['CH3CHO'],
            coefficients: { 'C2H2': 1, 'H2O': 1, 'CH3CHO': 1 },
            initialConcentrations: { 'C2H2': 0.4, 'H2O': 0.6, 'CH3CHO': 0.1 },
            equilibriumConstant: 5.0,
            deltaH: -125,
            initialTemp: 353,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['C2H2'],
            difficulty: 3
        },
        {
            id: 115,
            category: 'organic',
            equation: '2CH3CHO = CH3CH(OH)CH2CHO',
            displayEquation: '2CH<sub>3</sub>CHO ⇌ CH<sub>3</sub>CH(OH)CH<sub>2</sub>CHO',
            name: '乙醛醇醛缩合',
            description: '羟醛缩合反应',
            poeticDescription: '苯的硝化，硝基苯生，芳香化合物质变',
            reactants: ['CH3CHO'],
            products: ['CH3CH(OH)CH2CHO'],
            coefficients: { 'CH3CHO': 2, 'CH3CH(OH)CH2CHO': 1 },
            initialConcentrations: { 'CH3CHO': 0.6, 'CH3CH(OH)CH2CHO': 0.1 },
            equilibriumConstant: 0.8,
            deltaH: -25,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: false,
            difficulty: 3
        },
        {
            id: 116,
            category: 'organic',
            equation: 'C6H5OH + 3H2 = C6H11OH',
            displayEquation: 'C<sub>6</sub>H<sub>5</sub>OH + 3H<sub>2</sub> ⇌ C<sub>6</sub>H<sub>11</sub>OH',
            name: '苯酚加氢',
            description: '芳香族化合物加氢',
            poeticDescription: '甲苯氧化，苯甲酸成，侧链氧化显神威',
            reactants: ['C6H5OH', 'H2'],
            products: ['C6H11OH'],
            coefficients: { 'C6H5OH': 1, 'H2': 3, 'C6H11OH': 1 },
            initialConcentrations: { 'C6H5OH': 0.4, 'H2': 1, 'C6H11OH': 0.1 },
            equilibriumConstant: 1e12,
            deltaH: -315,
            initialTemp: 423,
            initialPressure: 500,
            hasGas: true,
            gasSpecies: ['H2'],
            difficulty: 3
        },
        {
            id: 117,
            category: 'organic',
            equation: 'C2H4 + Br2 = C2H4Br2',
            displayEquation: 'C<sub>2</sub>H<sub>4</sub> + Br<sub>2</sub> ⇌ C<sub>2</sub>H<sub>4</sub>Br<sub>2</sub>',
            name: '乙烯溴化',
            description: '加成反应',
            poeticDescription: '乙烯加氯，二氯乙烷，卤代烃中最简单',
            reactants: ['C2H4', 'Br2'],
            products: ['C2H4Br2'],
            coefficients: { 'C2H4': 1, 'Br2': 1, 'C2H4Br2': 1 },
            initialConcentrations: { 'C2H4': 0.5, 'Br2': 0.5, 'C2H4Br2': 0.1 },
            equilibriumConstant: 1e20,
            deltaH: -120,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['C2H4'],
            difficulty: 2
        },
        {
            id: 118,
            category: 'organic',
            equation: 'nC2H4 = (C2H4)n',
            displayEquation: 'nC<sub>2</sub>H<sub>4</sub> ⇌ (C<sub>2</sub>H<sub>4</sub>)<sub>n</sub>',
            name: '乙烯聚合',
            description: '聚合反应（简化模型，n=10）',
            poeticDescription: '乙炔加水，乙醛直生，三键开裂展奇观',
            reactants: ['C2H4'],
            products: ['(C2H4)n'],
            coefficients: { 'C2H4': 10, '(C2H4)n': 1 },
            initialConcentrations: { 'C2H4': 0.8, '(C2H4)n': 0.05 },
            equilibriumConstant: 1e30,
            deltaH: -900,
            initialTemp: 423,
            initialPressure: 1000,
            hasGas: true,
            gasSpecies: ['C2H4'],
            difficulty: 4
        },
        {
            id: 119,
            category: 'organic',
            equation: 'C6H12O6 = 2C2H5OH + 2CO2',
            displayEquation: 'C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> ⇌ 2C<sub>2</sub>H<sub>5</sub>OH + 2CO<sub>2</sub>↑',
            name: '葡萄糖发酵',
            description: '乙醇发酵反应',
            poeticDescription: '葡萄糖解，乙醇发酵，生物化学古今用',
            reactants: ['C6H12O6'],
            products: ['C2H5OH', 'CO2'],
            coefficients: { 'C6H12O6': 1, 'C2H5OH': 2, 'CO2': 2 },
            initialConcentrations: { 'C6H12O6': 0.3, 'C2H5OH': 0.2, 'CO2': 0.2 },
            equilibriumConstant: 1e10,
            deltaH: -75,
            initialTemp: 310,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CO2'],
            difficulty: 3
        },
        {
            id: 120,
            category: 'organic',
            equation: 'CH4 + Cl2 = CH3Cl + HCl',
            displayEquation: 'CH<sub>4</sub> + Cl<sub>2</sub> ⇌ CH<sub>3</sub>Cl + HCl',
            name: '甲烷氯代',
            description: '自由基取代反应',
            poeticDescription: '油脂皂化，甘油脂肪，日化工业源于此',
            reactants: ['CH4', 'Cl2'],
            products: ['CH3Cl', 'HCl'],
            coefficients: { 'CH4': 1, 'Cl2': 1, 'CH3Cl': 1, 'HCl': 1 },
            initialConcentrations: { 'CH4': 0.5, 'Cl2': 0.5, 'CH3Cl': 0.1, 'HCl': 0.1 },
            equilibriumConstant: 1e8,
            deltaH: -100,
            initialTemp: 298,
            initialPressure: 101,
            hasGas: true,
            gasSpecies: ['CH4', 'Cl2', 'CH3Cl', 'HCl'],
            difficulty: 3
        }
    ],

    /**
     * 为所有关卡兜底补齐诗意短句
     * - 不覆盖已手写的 poeticDescription
     * - 保持确定性（同一关卡每次生成一致）
     */
    ensurePoeticDescriptions() {
        if (this._poeticReady) return;
        this._poeticReady = true;

        const pools = {
            ionic: [
                '离子相逢，电荷牵引，沉淀如雪落杯底。',
                '一滴试剂，万千微粒，悄悄排出秩序。',
                '酸与碱握手言和，水在掌心轻声成形。'
            ],
            redox: [
                '得失之间皆是交换，电子奔走如流星。',
                '氧化与还原相对而行，像两条交错的河。',
                '电位起伏，胜负未定，平衡只差一念。'
            ],
            dissolution: [
                '溶与沉是一枚硬币的两面，静水里有暗潮。',
                '晶格松动，离子游走，杯中也有山河。',
                '饱和边缘最动人：刚好不多，恰好不少。'
            ],
            ionization: [
                '弱者不弱，慢慢电离，时间替它说话。',
                '水解如回声，在溶液深处反复轻响。',
                '酸碱不争高下，只争那一点点倾向。'
            ],
            complex: [
                '多重平衡叠成迷宫，出口总在下一步。',
                '络合与解离来回试探，像星群围绕引力。',
                '系统不喧哗，变量在暗处互相照亮。'
            ],
            electrochemistry: [
                '电流写下方向，反应把它读成命运。',
                '阴阳两极相望，离子在路上完成誓言。',
                '一端失去，一端得到，回路便有了光。'
            ],
            organic: [
                '碳链转身，官能团低语，万物皆可相逢。',
                '取代与加成像舞步，反应热是鼓点。',
                '有机的温柔在于选择：留下什么，带走什么。'
            ],
            custom: [
                '你写下的方程式，会在这里开花结果。',
                '创意不是偏离，而是另一种平衡。'
            ]
        };

        const defaultPool = [
            '平衡不是停滞，是两股力量相互成全。',
            '变化在继续，答案在途中。',
            '看似静止的刻度里，藏着最剧烈的往返。'
        ];

        const pick = (arr, seed) => arr[seed % arr.length];
        const safeStr = (v) => (typeof v === 'string' ? v.trim() : '');

        for (const level of this.levels) {
            if (!level) continue;
            const existing = safeStr(level.poeticDescription);
            if (existing) continue;

            const category = level.category;
            const pool = pools[category] || defaultPool;
            const seed = Number.isFinite(level.id) ? level.id : Math.abs(String(level.name || '').length);
            const base = pick(pool, seed);

            // 轻量“点题”：若有关卡名就拼接一句
            const name = safeStr(level.name);
            level.poeticDescription = name ? `${name}：${base}` : base;
        }
    },

    /**
     * 获取分类下的关卡
     */
    getLevelsByCategory(category) {
        this.ensurePoeticDescriptions();
        return this.levels.filter(level => level.category === category);
    },

    /**
     * 获取指定关卡
     */
    getLevel(id) {
        this.ensurePoeticDescriptions();
        return this.levels.find(level => level.id === id);
    },

    /**
     * 通过ID获取关卡（别名）
     */
    getLevelById(id) {
        return this.getLevel(id);
    },

    /**
     * 获取下一关
     */
    getNextLevel(currentId) {
        const currentIndex = this.levels.findIndex(level => level.id === currentId);
        if (currentIndex < this.levels.length - 1) {
            return this.levels[currentIndex + 1];
        }
        return null;
    },

    /**
     * 获取总关卡数
     */
    getTotalLevels() {
        return this.levels.length;
    }
};

// 导出
window.LevelData = LevelData;
